Document a new endpoint for origin/destination routing queries
chairemobilite/trRouting pull request #107
Opened 2022-01-13 19:39 UTC by tahini

This commit is the start of v2 of the trRouting API, where each query
will give access to a single functionality and parameters are
well-defined and for each query, all of the parameters can be set.

This endpoint returns a single transit routing calculation for the
origin/destination in parameter. It is a subset of the route/v1/transit
query, so return types are kept as they are in the original endpoint.

Note that this endpoint reverses the coordinates order of the
parameters. Origin and destination are now lon/lat, instead of lat/lon,
as mentioned in #100.

2022-01-13 20:49 UTC, kaligrafy approved these changes

2022-01-13 20:59 UTC, greenscientist requested changes
Some questions, 
requesting change to allow for discussion

2022-01-13 20:59 UTC, greenscientist commented on docs/API.yml
> +          name: scenario_uuid
I wonder if we should call it uuid or just scenario_id
I can envision that we could use with something else than transition, but still want to identifiy it's data source somehow. But have an UUID all the time seems a bit heavy. 
Thoughts?

2022-01-13 20:59 UTC, greenscientist commented on docs/API.yml
> +          description: UUID of the scenario to query. A scenario defines the services, agencies and lines to use for this transit calculation
We might want to specify that the scenario also define the timezone??
(I'm thinking about the time parameters later)

2022-01-13 20:59 UTC, greenscientist commented on docs/API.yml
> +            type: integer
with not bool?

2022-01-13 20:59 UTC, greenscientist commented on docs/API.yml
> +            type: integer
Reading the description, this feel it should be named some thing like time type and be an enum

2022-01-13 21:14 UTC, tahini commented on docs/API.yml
> +          name: scenario_uuid
Indeed, who knows what the future has in store for trRouting, scenario_id is nicer

2022-01-13 21:16 UTC, tahini commented on docs/API.yml
> +            type: integer
I don't know what other kind of time it can be. In the code, we use `forwardCalculation`, so it can be a boolean field called forward. I forgot boolean was allowed with openAPI, I just didn't use it before before it's too restrictive and the "boolean" fields were taking 1 as value instead of true, but here, it's a new endpoint, so might as well make it a boolean.

2022-01-13 21:22 UTC, greenscientist commented on docs/API.yml
> +            type: integer
I always have 3 choice when I use a routing app, let me check.

2022-01-14 14:01 UTC, tahini commented on docs/API.yml
> +            type: integer
Usually the third choice is "right now", no?

2022-01-14 14:10 UTC, tahini commented on docs/API.yml
> +                  - $ref: '#/components/schemas/success'
I'm keeping the responses as is, but the response has a lot of duplicate fields, like times in minutes AND seconds, sometimes even as human readable string. Should we keep only one of each, the field in seconds, from which, when required, we can calculate the other units? Is it trRouting's role to make those conversions or should it be the caller?

@kaligrafy what would be the impact on you to receive only the fields in seconds only? On the network, it should reduce the size of the response's body by close to the half. On the computation time, it's probably negligible.

2022-01-14 15:23 UTC, kaligrafy commented on docs/API.yml
> +                  - $ref: '#/components/schemas/success'
no problem getting the seconds only. Only old tools used the minutes.

2022-01-15 22:31 UTC, greenscientist commented on docs/API.yml
> +            type: integer
True. 
But now I've checked google maps and they have a Last Available option. 
So boolean or enum (we can just have 0, 1 for now but still allow for easy extention. 
Not attached to either solution.

2022-01-15 22:34 UTC, greenscientist commented on docs/API.yml
> +                  - $ref: '#/components/schemas/success'
Yeah second only. Since we send string anyway, it does  not impact much on data size. 
@kaligrafy I imagine we won't need millisecond precision on that kind of calculatioN?

2022-01-21 13:38 UTC, tahini commented on docs/API.yml
> +            type: integer
I named it time_type and left it an int in case we need to add options eventually, to not break the API

2022-01-21 13:40 UTC, tahini commented on docs/API.yml
> +                  - $ref: '#/components/schemas/successV2'
I added a v2 for success and noRoutingFound. I had to duplicate most of the return types to remove duplication and change the lat/lon to lon/lat formats.

2022-01-21 13:45 UTC, kaligrafy approved these changes

2022-01-21 13:46 UTC, kaligrafy commented on docs/API.yml
> +                  - $ref: '#/components/schemas/successV2'
I assume there will be another url route for routing from/to all stops for accessibility maps?

2022-01-21 13:59 UTC, tahini commented on docs/API.yml
> +                  - $ref: '#/components/schemas/successV2'
Yes, whenever another set of parameters is required, there will be another route. This avoids the trouble of complex parameter validation: if X is 0, then Y and Z ar required, but if X is 1, then either Y OR Z is required and what if both are set should we return a warning.... No, here, each param is either required or optional and if optional there is only one  default value for it, it's easy to validate, no possible error and if wrong, we return a query_error

2022-01-21 21:33 UTC, greenscientist reviewed
few more comments

2022-01-21 21:33 UTC, greenscientist commented on docs/API.yml
> +              description: Departure time as specified in the request, in seconds since midnight, or -1 if the departure time was not specified
I'm just curious, how to we handle change of day ?
Example: initial departure time is 23h55, but the actual departure is 00h05. Do we have an indication that it's the next day?

2022-01-21 21:33 UTC, greenscientist commented on docs/API.yml
> +              description: Departure time as specified in the request, in seconds since midnight, or -1 if the departure time was not specified
Also, do we need to replicate the intiialDepartureTime? Can we assume that the user knows this already?

2022-01-21 21:33 UTC, greenscientist commented on docs/API.yml
> +              type: number
Seems like this is covered by having departureTime and initialDepartureTime

2022-01-21 21:33 UTC, greenscientist commented on docs/API.yml
> +    routeResponseV2:
I'm already thinking of a good V3 for this type of response... :)

2022-01-21 21:33 UTC, greenscientist commented on docs/API.yml
> +          agencyUuid:
Why do we return the Name if we return the UUID?

2022-01-24 13:58 UTC, tahini commented on docs/API.yml
> +              description: Departure time as specified in the request, in seconds since midnight, or -1 if the departure time was not specified
I would keep the initialDepartureTime, it's an important parameter query and reminding it is very helpful. As for the change of day, in transit, days have more than 24 hours, so 00h05 would be 24h05 and 1h00 would be 25h00. But what if a trip is done partly with a night bus until 28h00, but ends with a day bus that starts at 4h30? @kaligrafy  would trRouting work for those trips?

2022-01-24 13:59 UTC, tahini commented on docs/API.yml
> +    routeResponseV2:
> I'm already thinking of a good V3 for this type of response... :)

Anything to say?

2022-01-24 14:06 UTC, tahini commented
In general, I see the response as a standalone json object that can be dumped somewhere and contains all the required information, some of which can be computed from the fields, and including the important query parameters (origin, destination, time and probably time_type to know if it was arrival or departure that was requested). 

That's why all the redundant unit fields are gone, and we can also remote the initialLostDepartureTime as it can be computed from other fields and is not required if it's an arrival time anyway.

As for the agency, name and uuid, I would keep both, as the uuid is important for a tool like transition to retrieve the lines and paths and get geojson of those segments, but it is meaningless for someone just reading a dump of the response, while the name tells right away which line/path were taken by the route. What do you think?

2022-01-24 18:37 UTC, tahini commented
Actually, the API version is in the API.yml file, so I think I should create a new file: APIv2.yml to put this new endpoint, and let the version be 2.0-beta. Then we can go ahead without feeling too committed to whatever is here and we can improve as all the new endpoints are added and their implementations are developped. How does that sound?

2022-01-27 13:57 UTC, tahini commented
The v2 API is officially in beta, so we won't have to feel too bad about changing it in a near future if we realize something better can be done, but we can go ahead with this at least. Also note that adding functionalities to a route (like an eventual cost function parameters) is not considered an API break and does not require major update

2022-01-27 20:40 UTC, greenscientist commented on docs/API.yml
> +    routeResponseV2:
Something more similar to the trip steps. Right now this responce object only assume  to walk and take bus/train. But we can combine other transport. (People in the suburbs takes their care to the train stop for example). So instead of a fixed list of parameters, we should combine it with the appropriate objects if needed

2022-01-27 20:42 UTC, greenscientist commented
> As for the agency, name and uuid, I would keep both, as the uuid is important for a tool like transition to retrieve the lines and paths and get geojson of those segments, but it is meaningless for someone just reading a dump of the response, while the name tells right away which line/path were taken by the route. What do you think?

Maybe we should have 2 query time then, one for machine consumption and one for more human needs?

2022-01-27 20:44 UTC, greenscientist commented
I guess the file split is ok if you say so :)

Maybe we should add a query to ask the server which queries version is support...

2022-01-27 20:56 UTC, tahini commented on docs/API.yml
> +    routeResponseV2:
You're pointing to a wide opened Pandora's box... Is it even trRouting's role to calculate the walking time? trRouting has its own way of calculating the walking time: either using osrm with a 'walking' profile (in our setup, get the wrong osrm port and you've got totally different results!), or use bird distance if no osrm server is available.

The walking steps results shows the times of those steps, _as calculated by trRouting_. But the tool that receives it (eg transition) and wants to display it as a geojson needs to calculate it again from the coordinates and that tools can very well have different results!

trRouting is the door for the connection scan algorithm (and eventually others) that find transit trips. Is multimodality its purpose? Maybe it is, but not in its current state. And if it does return trips for other modes, it should probably return the entire information to avoid the calling tool calculating again the geography with potentially different data.

But all this can be further API enhancements on v2, I don't think the proposition here is painting us in any corner.

2022-01-28 13:59 UTC, tahini commented
I added the /versions endpoint

2022-01-28 14:05 UTC, greenscientist commented
I'll approve this as is. I think we can do a lot more improvement to this API, but this probably imply more philosophical changes, that can go into a V3. This V2 is more about simplifying the API (I kinda think we might have too many fields still, but it's an improvement)

2022-01-28 14:05 UTC, greenscientist approved these changes

2022-01-28 15:53 UTC, merged