Add a RouteParameters class to store route query specific parameters
chairemobilite/trRouting pull request #108
Opened 2022-01-13 20:43 UTC by tahini

This class contains the parameters passed to a single routing query:
origin/destination, max/min times for waiting, access, egress, transfer,
etc and scenario data.

Add a factory method to create a parameters object from a parameters
vector.

Add unit tests for this factory method.

2022-01-13 20:44 UTC, tahini commented
This is the parameter parsing part of the new endpoint, as described in PR #107

2022-01-13 20:48 UTC, kaligrafy approved these changes

2022-01-13 21:20 UTC, greenscientist requested changes
Lots of small things

2022-01-13 21:20 UTC, greenscientist commented on connection_scan_algorithm/src/route_parameters.cpp
> +    Scenario* scenario_,
Can this be a reference instead? Can the pointer ever be null?

2022-01-13 21:20 UTC, greenscientist commented on connection_scan_algorithm/src/route_parameters.cpp
> +    scenarioUuid = scenario->uuid;
Answering my earlier question the pointer cannot be null, since we do not check for that case here.

2022-01-13 21:20 UTC, greenscientist commented on connection_scan_algorithm/src/route_parameters.cpp
> +    scenarioUuid = scenario->uuid;
We should copy from the data of the RouteParams and not the passed scenario one

2022-01-13 21:20 UTC, greenscientist commented on connection_scan_algorithm/src/route_parameters.cpp
> +    scenarioUuid = scenario->uuid;
Do we need to save the scenario pointer in the object since we extra the data at construction time?

2022-01-13 21:20 UTC, greenscientist commented on connection_scan_algorithm/src/route_parameters.cpp
> +  int getIntegerValue(std::string strValue) {
Feel that they should be in an helper class or at least static.

2022-01-13 21:20 UTC, greenscientist commented on connection_scan_algorithm/src/route_parameters.cpp
> +  RouteParameters createRouteODParameter(std::vector<std::pair<std::string, std::string>> &parameters, std::map<boost::uuids::uuid, int> &scenarioIndexesByUuid, std::vector<std::unique_ptr<Scenario>>
Maybe a comment of why we should use this function?

2022-01-13 21:20 UTC, greenscientist commented on connection_scan_algorithm/src/route_parameters.cpp
> +  RouteParameters createRouteODParameter(std::vector<std::pair<std::string, std::string>> &parameters, std::map<boost::uuids::uuid, int> &scenarioIndexesByUuid, std::vector<std::unique_ptr<Scenario>>
Also feel like a factory, should be static so that we don't need to instanciate a RouteParameters to call it

2022-01-13 21:20 UTC, greenscientist commented on connection_scan_algorithm/src/route_parameters.cpp
> +    int minWaitingTimeSeconds = 3 * 60;
All those number should be in constant

2022-01-13 21:20 UTC, greenscientist commented on connection_scan_algorithm/src/route_parameters.cpp
> +    for (auto & parameterWithValue : parameters)
Eventually, we should use a parsing library, but fine for now

2022-01-13 21:34 UTC, tahini commented on connection_scan_algorithm/src/route_parameters.cpp
> +    scenarioUuid = scenario->uuid;
I'll add a FIXME but unfortunately yes, because the alternatives calculation tweaks the exceptLine vector and a new object needs to be created. I have a TODO there (in the next yet-unexisting PR) to make this data a calculation parameter, but until then, it's easier to keep the scenario pointer in this object.

2022-01-13 21:36 UTC, tahini commented on connection_scan_algorithm/src/route_parameters.cpp
> +  int getIntegerValue(std::string strValue) {
definitely, it's just my lack of C++ knowledge that made it this way...

2022-01-13 21:37 UTC, tahini commented on connection_scan_algorithm/src/route_parameters.cpp
> +  RouteParameters createRouteODParameter(std::vector<std::pair<std::string, std::string>> &parameters, std::map<boost::uuids::uuid, int> &scenarioIndexesByUuid, std::vector<std::unique_ptr<Scenario>>
The comment is in the hpp file. Should I declare it as static there too? I guess yes

2022-01-14 14:24 UTC, tahini commented on connection_scan_algorithm/src/route_parameters.cpp
> +    Scenario* scenario_,
Can this be a reference? It's a unique_ptr that belongs to someone else, can I pass it around as reference? I'll have to read about this... But I think I tried and failed, but maybe just didn't try hard enough...

2022-01-14 14:26 UTC, tahini commented
I'll update this PR once the new route API is accepted.

2022-01-15 22:36 UTC, greenscientist commented on connection_scan_algorithm/src/route_parameters.cpp
> +  RouteParameters createRouteODParameter(std::vector<std::pair<std::string, std::string>> &parameters, std::map<boost::uuids::uuid, int> &scenarioIndexesByUuid, std::vector<std::unique_ptr<Scenario>>
Yes, the static should be in both instance, otherwise I think it's not the same function.

2022-01-28 14:38 UTC, tahini commented on connection_scan_algorithm/src/route_parameters.cpp
> +  RouteParameters createRouteODParameter(std::vector<std::pair<std::string, std::string>> &parameters, std::map<boost::uuids::uuid, int> &scenarioIndexesByUuid, std::vector<std::unique_ptr<Scenario>>
From my understanding of static functions in C (which is the same in C++?), static is scope limiting, that means if this factory were declared as static, it cannot be called from external file (I read https://stackoverflow.com/questions/42056160/static-functions-declared-in-c-header-files and other info on static keyword). Note that this function is a global function, outside the RouteParameters class. Did you mean it should be a public static method of the RouteParameters class? What would be the advantage versus global function like this?

2022-01-28 15:15 UTC, tahini commented on connection_scan_algorithm/src/route_parameters.cpp
> +    scenarioUuid = scenario->uuid;
Another option, instead of saving the scenario pointer would be to add a specific temporary constructor to create the alternatives RouteParameter object. Since it's temporary anyway, I prefer a temporary additional getter than a temporary constructor method (in case there are more such temporary constructors to implement, while the getter is one function and that's that), but it's not a strong opinion.

2022-02-07 23:41 UTC, greenscientist commented on connection_scan_algorithm/src/route_parameters.cpp
> +        alternatives(alt),
Detail, but we could have a more explicit variable name than alternatives. Something that fit more with a boolean, with an action maybe. Something like providesAlternative maybe

2022-02-08 19:19 UTC, greenscientist commented on connection_scan_algorithm/src/route_parameters.cpp
> +  RouteParameters createRouteODParameter(std::vector<std::pair<std::string, std::string>> &parameters, std::map<boost::uuids::uuid, int> &scenarioIndexesByUuid, std::vector<std::unique_ptr<Scenario>>
Static in C is not the same that in C++.   A Static function in a class in C++ means a function that can be called without having to create an instance

2022-02-13 16:37 UTC, greenscientist reviewed
Ok, just small comments in the test, otherwise rest looks good.

2022-02-13 16:37 UTC, greenscientist commented on tests/connection_scan_algorithm/route_parameters_test.cpp
> +        // Nothing to do? Shoud we delete the scenarios?
You might want to scenarios.clear() here. Otherwise you keep adding more seach time you call SetUp

2022-02-13 16:37 UTC, greenscientist commented on tests/connection_scan_algorithm/route_parameters_test.cpp
> +    std::map<boost::uuids::uuid, int> scenarioIndexesByUuid;
WHy not just a map witi UUID:Scenario ?

2022-02-14 13:30 UTC, tahini commented on tests/connection_scan_algorithm/route_parameters_test.cpp
> +    std::map<boost::uuids::uuid, int> scenarioIndexesByUuid;
It's the data type that is used in the trRouting code and that the route parameters factory expects. When we deal with how the data is stored, we can review this. But for now, this is the expected type and the scope of this branch is big enough as it is! (with the patches rewriting the query parameters waiting in line for review)

2022-02-14 13:32 UTC, tahini commented on tests/connection_scan_algorithm/route_parameters_test.cpp
> +        // Nothing to do? Shoud we delete the scenarios?
Done

2022-02-14 15:11 UTC, greenscientist approved these changes
Good enough. 

Next!

2022-02-14 15:11 UTC, greenscientist commented on tests/connection_scan_algorithm/route_parameters_test.cpp
> +        // Nothing to do? Shoud we delete the scenarios?
I would have say that we should remove the comment, but I'm not sure what we need to do with a std::make_unique, if we need to delete it manually of if it's automatic. So it's good to keep a TODO here.

2022-02-14 16:03 UTC, merged