Add new types for routing results
chairemobilite/trRouting pull request #121
Opened 2022-02-24 22:35 UTC by tahini

2022-02-24 22:39 UTC, tahini commented
@greenscientist This PR is not complete, I want to add some unit tests, and the PR that goes above (actually using those types) does not work yet, so there may be a bug here, but I'd like a high level review for now. I'll add the PR that uses it tomorrow.

2022-02-28 16:42 UTC, greenscientist requested changes
It's missing class description, so we know what are the intents. Probably need to scather more comments around. The visitor class needs to be explained more

A couple of small structural things to adresse

2022-02-28 16:42 UTC, greenscientist commented on include/routing_result.hpp
> +    std::string agencyAcronym;
That's a lot of element here, kind of wonder if they should be regrouped in a subobject

2022-02-28 16:42 UTC, greenscientist commented on include/routing_result.hpp
> +  class StepVisitorBase {
Not sure of it's role yet, but maybe a Visitor should be in its own file

2022-02-28 16:42 UTC, greenscientist commented on connection_scan_algorithm/include/result_to_response.hpp
> +  class ResultToV1Response: public ResultToResponse {
This probably need to be in a separate file

2022-03-07 18:44 UTC, tahini commented on include/routing_result.hpp
> +  class NoRoutingFoundResult : public RoutingResultNew {
I wonder if we need the NoRouting result, or if it should just be a nullptr...

2022-03-07 18:53 UTC, tahini commented on include/routing_result.hpp
> +  class NoRoutingFoundResult : public RoutingResultNew {
Actually a nullptr object cannot be visited, so it's probably better to keep this class

2022-03-07 19:06 UTC, tahini commented on include/routing_result.hpp
> +    std::string agencyAcronym;
Maybe an optimization for later, but with only the tripUuid and nodeUuid, we can get pretty much all the rest, given that we have access to the data (data, which is now contained within the calculator object, so it is far from a given that access to the data is available where/when we need it). It could be an optimization for later though. Once this is in, we can open a issue to track when/if we want to change this.

2022-03-07 19:08 UTC, tahini commented
@greenscientist  I updated as per your comments: more documentation and split visitor/result and converter/converter_to_v1 to separate files. I'll wait for your review of this PR before updating the next one.

2022-03-11 19:18 UTC, greenscientist commented on include/routing_result.hpp
> +  class NoRoutingFoundResult : public RoutingResultNew {
Do we need to convert a NoRouting result? Why would we need a visitor in this case?

2022-03-11 19:28 UTC, greenscientist reviewed
The class hierarchy seems to be lacking the top level. 
Am I missing something? Maybe it's lacking an high level doc/comment?

2022-03-11 19:28 UTC, greenscientist commented on include/routing_result.hpp
> +#include "routing_result_visitor.hpp"
Could probably just be a forward declaration instead I think

2022-03-11 19:28 UTC, greenscientist commented on include/routing_result.hpp
> +#include "point.hpp"
Could probably just be a forward declaration instead I think

2022-03-11 19:28 UTC, greenscientist commented on include/routing_result.hpp
> +  class StepRoutingResult {
SHould this inherit from RoutingResultNew?

2022-03-11 19:28 UTC, greenscientist commented on include/routing_result.hpp
> +  enum result_step_type { WALKING, BOARDING, UNBOARDING };
Shouldn't each of these type their own classes?

2022-03-11 20:08 UTC, tahini commented on include/routing_result.hpp
> +  class StepRoutingResult {
No, steps are not results. It's really how it's explained.

2022-03-11 20:09 UTC, tahini commented on include/routing_result.hpp
> +  enum result_step_type { WALKING, BOARDING, UNBOARDING };
They sort of are, but since we need to dynamically cast these enums are used to know which class to cast to. Is there a better way?

2022-03-11 20:22 UTC, tahini commented on include/routing_result.hpp
> +  class NoRoutingFoundResult : public RoutingResultNew {
As explained in the other PR, NoRouting is boring for now, but it will contain a reason later. Unless we use try catch and throw the no routing explanation, but no routing is a valid workflow and using error throwing for it it not necessarily good practice.

Another option would be to include the NoRoutingFound use case in the SingleCalculationResult since it's when it will happen.

What do you think? 3 options:

* the one in this PR (different class)
* try-catch
* merge with SingleCalculation
* other?

2022-03-27 12:44 UTC, greenscientist reviewed
Still a few small things

2022-03-27 12:44 UTC, greenscientist commented on include/routing_result.hpp
> +#include "point.hpp"
This ^^

2022-03-27 12:44 UTC, greenscientist commented on include/routing_result.hpp
> +#include "routing_result_visitor.hpp"
and this ^^

2022-03-27 12:44 UTC, greenscientist commented on include/routing_result.hpp
> +   * TODO: Even later, when function calls are detricated and split, there will be no use for a class hierarchy. Concrete result types
They could  still be in an hierarchy,  depending on the structure of the result. We'll need to see :)

2022-03-27 12:44 UTC, greenscientist commented on include/routing_result.hpp
> +  class StepRoutingResult {
Still wondering about the naming. I don't feel strongly about it, but maybe just RoutingStep ? To differenciate with RoutingResult ?

2022-03-27 12:44 UTC, greenscientist commented on include/routing_result.hpp
> +  class AccessibleNodesResult {
Maybe also not end this in Result if not a RoutingResult ?

2022-03-27 12:44 UTC, greenscientist commented on connection_scan_algorithm/include/result_to_v1.hpp
> +    nlohmann::json resultToJsonString(RoutingResultNew& result, RouteParameters& params) override;
You dropped the virtual here

2022-03-27 12:44 UTC, greenscientist commented on connection_scan_algorithm/include/result_to_v1.hpp
> +    nlohmann::json resultToJsonString(RoutingResultNew& result, RouteParameters& params) override;
Also, I would make them static. I don't see a need to instanciate a ResultToV1Response, we can just call the functions

2022-03-28 19:42 UTC, tahini commented on connection_scan_algorithm/include/result_to_v1.hpp
> +    nlohmann::json resultToJsonString(RoutingResultNew& result, RouteParameters& params) override;
Don't I need to drop the virtual if I'm implementing it? Also, for static calls, you need to know exactly which object to call. What if the code path can support both v1 and v2? sending the converter as base type object allows to just call this method on it and get whatever api version we require.

2022-03-28 19:45 UTC, greenscientist commented on connection_scan_algorithm/include/result_to_v1.hpp
> +    nlohmann::json resultToJsonString(RoutingResultNew& result, RouteParameters& params) override;
No, if you drop the virtual, you prohibit further inheritance. The différent is the absence of =0 which makes it virtual pure.

2022-03-28 19:45 UTC, greenscientist commented on connection_scan_algorithm/include/result_to_v1.hpp
> +    nlohmann::json resultToJsonString(RoutingResultNew& result, RouteParameters& params) override;
For the static, would need to  analyse the code a little  bit more. Depending on how it's used.

2022-03-28 20:06 UTC, tahini commented on include/routing_result.hpp
> +#include "point.hpp"
This one yes, can be forward declared

2022-03-28 20:06 UTC, tahini commented on include/routing_result.hpp
> +#include "routing_result_visitor.hpp"
This one no, we are calling methods from these classes.

2022-03-28 20:25 UTC, tahini commented on connection_scan_algorithm/include/result_to_response.hpp
> +#include "parameters.hpp"
I guess I can forward declare these here too?

2022-03-31 18:38 UTC, greenscientist commented on connection_scan_algorithm/include/result_to_response.hpp
> +#include "parameters.hpp"
Yeah probably. 
The json one is in a diffrent namespace, so might be annoying to forward declare, but the rest looks easy enough

2022-03-31 18:38 UTC, greenscientist commented on connection_scan_algorithm/include/result_to_v1.hpp
> +    virtual nlohmann::json resultToJsonString(RoutingResultNew& result, RouteParameters& params) override;
I guess override is a new keyword in C++!

2022-03-31 18:38 UTC, greenscientist commented on include/routing_result.hpp
> +#include "routing_result_visitor.hpp"
grumble. Not great to implement function in a .h, but ok.

2022-03-31 18:39 UTC, greenscientist commented on connection_scan_algorithm/include/result_to_v1.hpp
> +    nlohmann::json resultToJsonString(RoutingResultNew& result, RouteParameters& params) override;
For the static
you seem to be using it like this
      ResultToV1Response resultConverter = ResultToV1Response();
            response = resultConverter.resultToJsonString(alternativeResult, routeParams).dump(2);
You are now using any inheritence property here. 
Instead, if it was static, you could simply do
   response = ResultToV1Response::resultToJsonString(alternativeResult, routeParams).dump(2);

2022-03-31 18:40 UTC, greenscientist commented
Almost there, a few forward declaration, and the discussion about the static function.

2022-03-31 19:40 UTC, tahini commented
I did the static for the result and a bit of forward declaration in result_to_v1.hpp

2022-03-31 20:32 UTC, greenscientist approved these changes
Ok, let's go for this!

2022-03-31 20:39 UTC, merged