csa: Update calculation methods to return new result objects
chairemobilite/trRouting pull request #122
Opened 2022-02-25 19:52 UTC by tahini

2022-02-25 19:58 UTC, tahini commented
@greenscientist First 2 commits are part of #121 Only the last one is to be reviewed independently. And it works with Transition!

ftr, I haven't changed any logic anywhere, just the return values of the functions (and how they are built).

It's making use the unique_ptr for the result object and there's a bit of those. I'll [try to] run valgrind on this to make sure it's not introducing any memory leaks. But let me know if there's anything obviously wrong here please!

2022-02-28 16:51 UTC, greenscientist requested changes
Please explain the the commit message why you added all the unique_ptr

That plus probably add more comments in general

2022-02-28 16:51 UTC, greenscientist commented on connection_scan_algorithm/include/calculator.hpp
> +    // TODO This function supporst both allNodes and simple calculation, which
supporst

2022-02-28 16:51 UTC, greenscientist commented on connection_scan_algorithm/src/alternatives_routing.cpp
> +  class LineIdxStepVisitor : public StepVisitor<int> {
What's a LineIdxStepVisitor

2022-02-28 16:51 UTC, greenscientist commented on connection_scan_algorithm/src/reverse_journey.cpp
> +                singleResult.get()->steps.push_back(std::make_unique<StepWalkingRoutingResult>(
I would add a comment here to explain what it going on

2022-02-28 16:51 UTC, greenscientist commented on connection_scan_algorithm/src/reverse_journey.cpp
> +    std::unique_ptr<RoutingResult> result = std::make_unique<NoRoutingFoundResult>();
I don't really get why all the unique_ptr here

2022-02-28 17:05 UTC, tahini commented on include/routing_result.hpp
> +    Point& nodeCoordinates;
About the unique_ptr, I'm not sure it still applies, I've been through a lot with this patch... I'll check next week. But the main reason for them is that the copy constructor for these classes didn't work to pass result objects as objects. I don't remember if it was the Point here or the vectors that were causing compilation errors, but the pointers ended up working and it remained this way...

2022-03-07 18:12 UTC, tahini commented
So after trying to remove the unique_ptr, it turns out that it is not possible to return by value an object of an abstract type and the return values cannot be of concrete types, as methods can return one of many (for example, no result, alternatives or singleCalculation). The option of reference does not work as the object are created in the function (on the stack) and do not exist once out of the function. Returning a pointer is the way to go, and to avoid memory leaks, unique_ptr are used.
@greenscientist  If you think of any other way, or how to refactor the code to avoid that, let me know!

2022-03-11 19:15 UTC, greenscientist commented on connection_scan_algorithm/src/forward_journey.cpp
> +    return std::move(result);
Is this std::move required?

2022-03-11 19:15 UTC, greenscientist commented on connection_scan_algorithm/include/calculator.hpp
> +    std::unique_ptr<RoutingResult> alternativesRouting(RouteParameters &parameters);
Ok, finally found what was bugging me with this. Why all these function return the same type of results? They should be their own result type. This would allow to have a concrete return results, which is a child of RoutingResult. 
Thoughts ?

2022-03-11 19:16 UTC, greenscientist commented
@tahini See my latest comment

2022-03-11 20:07 UTC, tahini commented on connection_scan_algorithm/include/calculator.hpp
> +    std::unique_ptr<RoutingResult> alternativesRouting(RouteParameters &parameters);
I agree, but this would require MAJOR refactoring of the code, and that's outside the scope of this PR or the next or the next next. These methods cover both the allNodes case (for accessibility maps) and the normal calculation.

Why am I doing this PR again? (need to remind myself sometimes...) I want trRouting to have a well-defined API that we can trust (not just look at the result of one query and hope it's always the same) and build upon (and make sure the implementation matches the defined API). 
And then we want to be able to return more specific responses than just no_routing or error. Why is there no_routing? origin and/or destination are not accessible? Are there trips in the scenario around the O/D or just none at all anywhere? So while the NoRoutingFound return type may seem trivial now, it may contain more info later, unless we decide to use error throwing for the various use cases and [eventually later later] have a concrete return type.

2022-03-17 13:33 UTC, tahini commented
@greenscientist It is updated with the latest changes to the result classes. As discussed offline, the no routing is now an exception. And the alternative routing returns a concrete type instead of unique_ptr, because it can. So there's only the allNodes/single calculation to eventually split to be able to get only concrete results and no pointers.

2022-03-27 13:08 UTC, greenscientist requested changes
Mostly nits, comments and naming

2022-03-27 13:08 UTC, greenscientist commented on connection_scan_algorithm/include/calculator.hpp
> +    // TODO This function supporst both allNodes and simple calculation, which
Still there

2022-03-27 13:08 UTC, greenscientist commented on connection_scan_algorithm/include/result_to_response.hpp
> +    virtual nlohmann::json resultToJsonString(RoutingResult& result, RouteParameters& params) = 0;
I don't understand why you drop the New here, speciall that you just added this class

2022-03-27 13:08 UTC, greenscientist commented on connection_scan_algorithm/src/forward_journey.cpp
>      if (foundLine || params.returnAllNodesResult)
Technically, with the throw you added, this  if is not required anymore. 
(but we should keep a comment stating that)

2022-03-27 13:08 UTC, greenscientist commented on connection_scan_algorithm/src/forward_journey.cpp
>            i++;
I don't see this i++ being used. (I know, you did not changed it, but just to reduce line count... :)

2022-03-27 13:08 UTC, greenscientist commented on connection_scan_algorithm/src/forward_journey.cpp
>          i = 0;
The i I mentionned earlier is reset here.

2022-03-27 13:08 UTC, greenscientist commented on connection_scan_algorithm/src/od_trips_routing.cpp
> +    // This type of result should not be visited here
Do we need an assert?? The comment make me feel like it

2022-03-27 13:08 UTC, greenscientist commented on connection_scan_algorithm/src/reverse_journey.cpp
> +      allNodesResult.get()->percentOfReachableNodes = round(10000 * (float)reachableNodesCount / (float)(nodesCount))/100.0;
Eventuelly, the presence eof 10000 * should be explained here.

2022-03-27 13:08 UTC, greenscientist commented on connection_scan_algorithm/src/transit_routing_http_server.cpp
> +        std::cerr << "-- total -- " << calculator.algorithmCalculationTime.getDurationMicrosecondsNoStop() << " microseconds\n";
Just a "note to shelf", we'll need proper logging at some point!

2022-03-27 13:08 UTC, greenscientist commented on include/routing_result.hpp
> +  class RoutingResult {
I think I would make the renaming from New to not New in a separate commit. Would make this one easier to follow (not necessary if too complicated to extricate)

2022-03-27 14:42 UTC, tahini commented on connection_scan_algorithm/src/calculator.cpp
> +  std::unique_ptr<RoutingResult> Calculator::calculate(RouteParameters &parameters, bool resetAccessPaths, bool resetFilters) {
Just wondering, could this be a struct union of SingleCalculation, AllNodes and maybe NoRoutingFound instead of unique_ptr and throw NoRoutingFound? Since the alternative routing depends on the noRoutingFound answer, it's like the main workflow depending on try/catch. I see slight performance degradation for alternatives calculations when many there are many alternatives. Could the try/catch be the cause?

2022-03-27 15:32 UTC, greenscientist commented on connection_scan_algorithm/src/calculator.cpp
> +  std::unique_ptr<RoutingResult> Calculator::calculate(RouteParameters &parameters, bool resetAccessPaths, bool resetFilters) {
Not sure what you are refering to as "this". 
But in general, struct union are a bit hard to understand and more useful to save space than to control flow of a program and more "C" than "C++"

Is the try catch in a loop? Yes, having some error handling is a bit slower. But there's s lot of change in this patch, hard to pinpoint the culprit. Did you generate a flame graph to at least narrow down the function?

2022-03-28 21:02 UTC, tahini commented on connection_scan_algorithm/src/calculator.cpp
> +  std::unique_ptr<RoutingResult> Calculator::calculate(RouteParameters &parameters, bool resetAccessPaths, bool resetFilters) {
Indeed the try catch is in a loop, to try all possible combinations of lines, so it is expected to have quite a few noRoutingFound results. And I did not do any profiling. For what it's worth, it may be my setup, the difference is not big enough to be worth investigating at this point, but since I wasn't expecting that difference, I doubted...

Let's leave it like this for now, refactor quite a few more things, and then revisit this issue later. Maybe this will be completely different anyway!

2022-03-28 21:03 UTC, tahini commented on connection_scan_algorithm/src/reverse_journey.cpp
> +      allNodesResult.get()->percentOfReachableNodes = round(10000 * (float)reachableNodesCount / (float)(nodesCount))/100.0;
Indeed, why not just *100?

2022-03-30 01:56 UTC, tahini commented
@greenscientist  some of your comments are addressed in #123 (renaming the RoutingResultNew class, removing some i's)

2022-03-30 12:45 UTC, tahini commented
For the performance issue, I had another hypothesis, which was my own setup (I had enabled kibana and elasticsearch just to test with photon and it surprisingly takes a lot of resources with an empty database and a idle computer...). After disabling them, this has better performances in 45/48 test cases, as expected since we don't create the json response during calculation anymore.

2022-03-31 18:29 UTC, greenscientist commented on connection_scan_algorithm/src/reverse_journey.cpp
> +      allNodesResult.get()->percentOfReachableNodes = round(10000 * (float)reachableNodesCount / (float)(nodesCount))/100.0;
Indeed. hightight why we need a comment :)

2022-03-31 18:29 UTC, greenscientist commented on connection_scan_algorithm/src/calculator.cpp
> +  std::unique_ptr<RoutingResult> Calculator::calculate(RouteParameters &parameters, bool resetAccessPaths, bool resetFilters) {
Yeah, probably better to run profiling after the end of the refactoring

2022-03-31 20:47 UTC, greenscientist approved these changes
ok, let's go with this. 
if it was new code I would have been more critical, but we are refactoring, so improvment can more later.

2022-03-31 20:47 UTC, greenscientist commented on connection_scan_algorithm/src/forward_journey.cpp
> +      std::cerr << "-- forward result: " << (params.returnAllNodesResult ? " allNodes " : "single calculation") << std::endl;
Eventually, this should go throught a proper logging class

2022-03-31 21:01 UTC, merged