don't include project shortname in custom cache
chairemobilite/trRouting pull request #145
Opened 2022-06-14 19:04 UTC by kaligrafy

when providinf a custom cache directory path, we should not add the project shortname to the path, because it should be included if needed in the custom path, this fix problem with Transition sending custom paths for simulations

2022-06-14 19:11 UTC, tahini requested changes

2022-06-14 19:11 UTC, tahini commented on src/cache_fetcher.cpp
> +    if (params.cacheDirectoryPath.empty() && !params.projectShortname.empty()) {
This should be an else if to the previous if. It makes sure that those 2 ifs are mutually exclusive. You will never enter both. If this is what you mean.

2022-06-14 21:08 UTC, kaligrafy commented on src/cache_fetcher.cpp
> +    if (params.cacheDirectoryPath.empty() && !params.projectShortname.empty()) {
fixed

2022-06-15 11:06 UTC, kaligrafy commented on src/cache_fetcher.cpp
> +    if (params.cacheDirectoryPath.empty() && !params.projectShortname.empty()) {
fixed test also

2022-06-15 13:40 UTC, tahini submitted a review, later dismissed

2022-06-15 13:40 UTC, tahini commented on src/cache_fetcher.cpp
> +    else if (!params.projectShortname.empty()) {
Why don't we just send the cacheDirectoryPath, which would include the project shortname in the default case? This looks weird and I always found it hard to figure out where to put the cache when running trRouting manually by default. We should have one cacheDirectoryPath, absolute, document it, and that's it. If there isn't already, we should open an issue. Because this is uselessly complicated imho...

2022-06-15 13:55 UTC, kaligrafy commented on src/cache_fetcher.cpp
> +    else if (!params.projectShortname.empty()) {
because json2capnp expect the default to include the project shortname... We should discuss this in an issue

2022-06-15 13:55 UTC, merged

2022-06-15 14:22 UTC, tahini commented
Hey you merged even if I removed my approval!