Introduce a base class DataFetcher as parent to CacheFetcher
chairemobilite/trRouting pull request #161
Opened 2022-07-07 18:19 UTC by greenscientist

Instead of having a if on the data source type in preparation.cpp which calls
different functions, we create the infrastructure to simple parse the type in
the main and instantiate the appropriate Fetcher there and pass it to
the Calculator

This simple some functions and remove need for a few parameters in the Parameters class

2022-07-07 18:40 UTC, tahini requested changes

2022-07-07 18:40 UTC, tahini commented on connection_scan_algorithm/src/transit_routing_http_server.cpp
> +    //TODO This is not destroyed on shutdown
What about the fetcher.delete() below?

2022-07-07 18:40 UTC, tahini commented on include/data_fetcher.hpp
> +  class Person;
Some bad alignments in this file, visible in github if not in your editor

2022-07-07 18:40 UTC, tahini commented on include/cache_fetcher.hpp
> +    virtual const std::pair<std::vector<Mode>, std::map<std::string, int>> getModes();
Do they really need to be repeated here since they are already in the base class? Maybe remove the docs from the methods since it is a copy of the one from data_fetcher and they may eventually diverge.

2022-07-07 18:40 UTC, tahini commented on include/parameters.hpp
>    class DatabaseFetcher;
Can you remove this too?

2022-07-07 18:40 UTC, tahini commented on connection_scan_algorithm/include/calculator.hpp
> +    Parameters params;
Is this really needed?

2022-07-07 18:53 UTC, greenscientist commented on connection_scan_algorithm/include/calculator.hpp
> +    Parameters params;
Yes, calculator need a Parameters object to operate. It was initially given to it in the main().

2022-07-07 18:54 UTC, greenscientist commented
(fixing the failing test, I don't know why this make check did not run locally before I submitted the PR)

2022-07-07 19:16 UTC, greenscientist commented on include/parameters.hpp
>    class DatabaseFetcher;
Yup!  Someday, we might add DBFetcher :)

2022-07-07 19:17 UTC, greenscientist commented on include/cache_fetcher.hpp
> +    virtual const std::pair<std::vector<Mode>, std::map<std::string, int>> getModes();
Yes, the function need to be repeated. The base class has virtual pure functions, here it's an actual implementation. 

About the documentation, yes, it should probably be only in the base class.

2022-07-07 19:18 UTC, greenscientist commented on connection_scan_algorithm/src/transit_routing_http_server.cpp
> +    //TODO This is not destroyed on shutdown
Forgot to remove the TODO once I did the cleanup :)

2022-07-07 19:23 UTC, tahini commented on tests/connection_scan_algorithm/csa_test_base.hpp
> +#include "dummy_data_fetcher.hpp"
Did you forget to add this file?

2022-07-07 19:27 UTC, greenscientist commented on tests/connection_scan_algorithm/csa_test_base.hpp
> +#include "dummy_data_fetcher.hpp"
Yes!

2022-07-11 13:41 UTC, tahini approved these changes
Sounds good, does it require changes to the command line? See the program option comment.

2022-07-11 13:41 UTC, tahini commented on connection_scan_algorithm/src/preparations.cpp
> +    ret = updateNodesFromCache();
These methods will eventually need to be renamed

2022-07-11 13:41 UTC, tahini commented on include/dummy_data_fetcher.hpp
> +  /** Dummy class, to be used in tests
iiuc it doesn't do anything now. But we could (and maybe eventually will have to) use it to fill mock data. If so, maybe add comments here to explain its eventual role in test, or just to say it does nothing at all.

2022-07-11 13:41 UTC, tahini commented on connection_scan_algorithm/src/transit_routing_http_server.cpp
> +  if (programOptions.dataFetcherShortname == "cache") {
Is this a new program option to specify? Or is it the default?

2022-07-11 13:42 UTC, greenscientist commented on connection_scan_algorithm/src/transit_routing_http_server.cpp
> +  if (programOptions.dataFetcherShortname == "cache") {
It's the default. It was already using this (but elsewhere in the code.

2022-07-11 13:45 UTC, greenscientist commented on connection_scan_algorithm/src/preparations.cpp
> +    ret = updateNodesFromCache();
Yeah, it was on my TODO list, but seems like I did not write it down.

2022-07-11 13:45 UTC, greenscientist commented on include/dummy_data_fetcher.hpp
> +  /** Dummy class, to be used in tests
ok

2022-07-11 14:16 UTC, merged