Migrate DataSource vector and index map to a single UUID:DataSource map
chairemobilite/trRouting pull request #168
Opened 2022-07-19 21:04 UTC by greenscientist

Added == and != operators to DataSource

Since Person and OdTrip now store a reference to a DataSource, we added constructor for those.

While doing this, we observed that Households and Places are not used anywhere in the calculation.
We have commented out those files, references and initialization functions. Those were marked
with a TODO #167 (task number to restore them when needed/refactoring done)

Tested with Transition

2022-07-25 18:38 UTC, tahini requested changes
A c++ question and alignment issues

2022-07-25 18:38 UTC, tahini commented on include/parameters.hpp
> +    std::optional<DataSource> onlyDataSource;
check alignments in this file

2022-07-25 18:38 UTC, tahini commented on src/data_sources_cache_fetcher.cpp
> +        ts[t.uuid] = t;
So there is no unique_ptr anymore, so iiuc now we have a map of objects and the `at` method of the map returns a & to the object? This line here copies the entire object? Do we have/need a copy constructor? Has it been tested?

2022-07-26 17:37 UTC, greenscientist commented on src/data_sources_cache_fetcher.cpp
> +        ts[t.uuid] = t;
Yes, it copies the whole object. 
We don't need an explicit copy constructor, the default one will do the job. 

As for testing, it seems to work with Transition.

2022-07-27 14:01 UTC, greenscientist commented on include/parameters.hpp
> +    std::optional<DataSource> onlyDataSource;
updated

2022-07-27 14:02 UTC, greenscientist commented
(and rebased)

2022-07-27 17:34 UTC, tahini approved these changes
Looks ok, I'm really really looking forward for multi-threaded trRouting, so by all means, go ahead!!

2022-07-27 18:49 UTC, greenscientist commented
> Looks ok, I'm really really looking forward for multi-threaded trRouting, so by all means, go ahead!!

still a long way to go :/

2022-07-27 18:49 UTC, merged