Migrate Line vector and index map to a single UUID:Line map
chairemobilite/trRouting pull request #173
Opened 2022-08-02 20:54 UTC by greenscientist

There was a few cases where the LineIndex was saved but not used, so those where removed.
This include the ConnectionTuple, which included a LineIdx.

In areas where you had a Trip object, the Line object can be accessed directly instead of
going to the full vector

Combination class had to be changed to be able to accommodate std::reference_wrapper.

2022-08-02 21:23 UTC, greenscientist commented
(Tested with transition)

2022-08-03 13:53 UTC, tahini requested changes
This review has been giving me headaches in the alternatives calculation. Are you confident that all alternative are still returned? Unit tests have very basic tests for those (there's only the except from the first result, not enough lines for more exceptions after that). Maybe in the benchmark, you can output the number of alternatives and make sure they match in both cases?

2022-08-03 13:53 UTC, tahini commented on include/combinations.hpp
> +// With later  modifications to adapt for std::reference_wrapper
Would it be worth adding unit tests for this class? Or are you confident enough with your changes and the stability of this class?

2022-08-03 13:53 UTC, tahini commented on connection_scan_algorithm/src/alternatives_routing.cpp
> +      for (int k = 1; k <= foundLines.size(); k++)
Some comments on what the blocks do in this function would be really nice. It's giving me headaches to understand. It fills the allCombinations vector with all combinations of 1 up to n of the lines found in the best result, so each combination can be added as exceptLines later?

2022-08-03 13:53 UTC, tahini commented on connection_scan_algorithm/src/alternatives_routing.cpp
> +              LineIdxVisitor alternativeVisitor = LineIdxVisitor(lines);
Maybe change the name of the Visitor class since it does not return idx anymore?

2022-08-03 13:53 UTC, tahini commented on connection_scan_algorithm/src/alternatives_routing.cpp
> +                    // Add current exclusion combination to the new exclusion
Why? what's happening here?

2022-08-03 13:53 UTC, tahini commented on connection_scan_algorithm/src/od_trips_routing.cpp
> +      lineProfiles[line.first] = 0.0;
.first? Or name it lineIter like below to avoid confusion, as this is not a Line, but a  key, value pair.

2022-08-03 13:53 UTC, tahini commented on include/line.hpp
> +  inline bool operator<(const std::reference_wrapper<const TrRouting::Line>& lhs, const std::reference_wrapper<const Line>& rhs)
No need for >, >=, <=?

2022-08-03 13:53 UTC, tahini commented on tests/connection_scan_algorithm/csa_test_base.cpp
> +  spdlog::set_level(spdlog::level::debug);
Keep or remove? If keep, add whitespaces to match the rest of the file

2022-08-03 15:11 UTC, greenscientist commented on include/combinations.hpp
> +// With later  modifications to adapt for std::reference_wrapper
The change I did is only doing a copy of the result at the end to remove the optional, so quite that it did not change the previous behavior.

2022-08-03 15:11 UTC, greenscientist commented
Yeah, it has been giving me headaches too. :)

As for number of alternative, at least in transition i'm getting the same results as before. 
I did inspect the debug log during the tests and I was getting the same number of alternative. (I enabled debug during the benchmark during my tests and the number matched)

2022-08-03 15:12 UTC, greenscientist commented on connection_scan_algorithm/src/alternatives_routing.cpp
> +                    // Add current exclusion combination to the new exclusion
You are asking about the additional comment or the code change?
(I just changed the code because a std::copy felt easier to understand)

2022-08-03 15:19 UTC, tahini commented on connection_scan_algorithm/src/alternatives_routing.cpp
> +                    // Add current exclusion combination to the new exclusion
I'm asking for additional comments on what this does. It's really not obvious what's happening here and since you did the head banging work of understanding the function, you might as well share this in comments ;-)

2022-08-03 17:13 UTC, greenscientist commented on connection_scan_algorithm/src/alternatives_routing.cpp
> +      for (int k = 1; k <= foundLines.size(); k++)
Yeah, that's basically it

2022-08-03 17:14 UTC, greenscientist commented on include/line.hpp
> +  inline bool operator<(const std::reference_wrapper<const TrRouting::Line>& lhs, const std::reference_wrapper<const Line>& rhs)
No,  sort and std::map only rely on <

2022-08-03 17:15 UTC, greenscientist commented on tests/connection_scan_algorithm/csa_test_base.cpp
> +  spdlog::set_level(spdlog::level::debug);
I kind of like having full debug in the tests output. So if you don't might I'll leave it there (propelly aligned)

2022-08-03 19:37 UTC, greenscientist commented on include/combinations.hpp
> +// With later  modifications to adapt for std::reference_wrapper
Adding basic tests

2022-08-03 19:37 UTC, greenscientist commented on connection_scan_algorithm/src/alternatives_routing.cpp
> +                    // Add current exclusion combination to the new exclusion
Tried adding a few comments, but I think the code could be simplified eventually.

2022-08-03 19:45 UTC, greenscientist commented
Some fix.
There was already some test checking the number of alternative result, so that should at least do some basic coverage. (In addition to the manual comparison I have done in the benchmark)

2022-08-04 17:36 UTC, tahini approved these changes
Some remaining comments that you may fix before merging or not.

2022-08-04 17:36 UTC, tahini commented on tests/connection_scan_algorithm/combinations_test.cpp
> +/*class CombinationTests : public ::testing::Test
Remove commented code

2022-08-04 17:36 UTC, tahini commented on connection_scan_algorithm/src/od_trips_routing.cpp
> +    //TODO Why is it 28 ? That seems too many hours in a day
In transit, it is habitual to have schedules from midnight to 4AM the next day, whence 28. But I don't know how common it is, if it is a rule, if it works everywhere, if it should rather be configured per agency, etc. @kaligrafy may know

2022-08-06 16:59 UTC, greenscientist commented on connection_scan_algorithm/src/od_trips_routing.cpp
> +    //TODO Why is it 28 ? That seems too many hours in a day
ok. make sense, but having it hardcoded seems wrong. As you say, we should either infer from the available data. 
I imagine not all agency will have that.

2022-08-06 17:16 UTC, merged