Implement the `v2/route` and `v2/summary` endpoints
chairemobilite/trRouting pull request #181
Opened 2022-09-20 20:22 UTC by tahini

Fixes #177 

@greenscientist I don't think it has any impact on the refactoring you are doing...

2022-09-20 21:17 UTC, greenscientist commented
Yeah,should not conflict much.
(I'll check the code  in more depth tomorrow)

2022-09-23 17:33 UTC, kaligrafy commented
I'll let @greenscientist review this one

2022-09-27 18:23 UTC, greenscientist requested changes
Two things to revisit, I'll let you comment if it's possible to do or not.

2022-09-27 18:23 UTC, greenscientist commented on connection_scan_algorithm/src/transit_routing_http_server.cpp
> +std::string intializeResponseNew(Calculator::DataStatus status)
I don't see how the function name match what it does. Seems to convert a Status object to json

2022-09-27 18:23 UTC, greenscientist commented on connection_scan_algorithm/src/transit_routing_http_server.cpp
> +    std::string response = intializeResponseNew(dataStatus);
Is it possible to put most of this code in a function? Would be easier to move around instead of putting it directly into the parsing code.  It fees like there's a lot of copy/paste here. Would at least add comments explaining the copy/paste.

2022-09-27 18:23 UTC, greenscientist commented on connection_scan_algorithm/src/transit_routing_http_server.cpp
> +  server.resource["^/v2/summary[/]?$"]["GET"]=[&server, &calculator, &dataStatus](std::shared_ptr<HttpServer::Response> serverResponse, std::shared_ptr<HttpServer::Request> request) {
Basically same comment about puting in a function. At least you have a comment here.

2022-09-27 18:54 UTC, tahini commented on connection_scan_algorithm/src/transit_routing_http_server.cpp
> +std::string intializeResponseNew(Calculator::DataStatus status)
Good point, that was taken from a branch I started months ago... I'll update

2022-09-27 19:01 UTC, tahini commented on connection_scan_algorithm/src/transit_routing_http_server.cpp
> +    std::string response = intializeResponseNew(dataStatus);
Possible yes, desirable, yes too. But whatever part of the code is moved out should be web server independent, so we'd need to determine where to put the split, how much can be re-used from v1 to v2 (technically, the difference is only the API, so much should be common). From my previous experimentations with this function, I think it could be easier when the routingResult doesn't have to be a unique_ptr (probably after all the refactoring is done). For now, I think I'll just add a comment... and hopefully get to rewrite this before there,s too much new APIs.

2022-09-28 17:01 UTC, greenscientist approved these changes

2022-09-28 17:01 UTC, merged