Initial files for an autotools based build system.
chairemobilite/trRouting pull request #19
Opened 2021-01-22 20:30 UTC by greenscientist

To initialize, run autoreconf -i

Tested with both gcc and clang, only on Debian Linux

Next steps: 
 * Generate capnp based .h files automatically (#13)
 * Manage herder files 
 * Update documentation

Issue #12

2021-01-22 20:43 UTC, kaligrafy commented
capnp files have changed in transition recently. We must update them in trRouting.

2021-01-25 16:42 UTC, greenscientist commented
> capnp files have changed in transition recently. We must update them in trRouting.

That's a separate issue ;-)

2021-01-27 16:49 UTC, greenscientist commented
Added a new commit to the stack to autogen the capnp headers.

2021-02-01 18:51 UTC, tahini requested changes
I'm sure I'll love it once it works :D 

Also, could you please update the README accordingly with new build instructions.

2021-02-01 18:51 UTC, tahini commented on configure.ac
> +AX_CXX_COMPILE_STDCXX_14(noext)
I have this error here:
```
checking how to hardcode library paths into programs... immediate
./configure: line 15912: syntax error near unexpected token `noext'
./configure: line 15912: `AX_CXX_COMPILE_STDCXX_14(noext)'
```

What am I missing?

2021-02-01 18:57 UTC, greenscientist commented
what is your version of autotools? (and on what Linux Distro/version are
you building on?

On Mon, Feb 1, 2021 at 1:51 PM Geneviève Bastien <notifications@github.com>
wrote:

> *@tahini* requested changes on this pull request.
>
> I'm sure I'll love it once it works :D
>
> Also, could you please update the README accordingly with new build
> instructions.
> ------------------------------
>
> In configure.ac
> <https://github.com/kaligrafy/trRouting/pull/19#discussion_r568058741>:
>
> > @@ -0,0 +1,53 @@
> +AC_INIT([trRouting], [1.0], [TODO@TODO.PRG])
> +AM_INIT_AUTOMAKE([-Wall -Werror foreign])
> +
> +AC_PROG_CC
> +AC_PROG_CXX
> +AM_PROG_AR
> +
> +LT_INIT
> +
> +# AX_ macros from on autoconf-archive
> +
> +# TODO Do we need the strict mode or not here ?
> +AX_CXX_COMPILE_STDCXX_14(noext)
>
> I have this error here:
>
> checking how to hardcode library paths into programs... immediate
> ./configure: line 15912: syntax error near unexpected token `noext'
> ./configure: line 15912: `AX_CXX_COMPILE_STDCXX_14(noext)'
>
> What am I missing?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kaligrafy/trRouting/pull/19#pullrequestreview-580660639>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABDR5PCSI26MMF224TYUADS43Z37ANCNFSM4WPAE3EA>
> .
>

2021-02-01 19:00 UTC, tahini commented
Ubuntu 18.04 and autoreconf 2.69

2021-02-01 19:03 UTC, greenscientist commented
Do you have autoconf-archive installed ?

On Mon, Feb 1, 2021 at 2:01 PM Geneviève Bastien <notifications@github.com>
wrote:

> Ubuntu 18.04 and autoreconf 2.69
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kaligrafy/trRouting/pull/19#issuecomment-771082361>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABDR5PQ2UQQG5MU7B74XTDS4327HANCNFSM4WPAE3EA>
> .
>

2021-02-01 19:18 UTC, tahini commented
> Do you have autoconf-archive installed ?

I did not, it thus now seems to work! With the resulting application in the src/ folder.

Could you please update the README with all those steps? You can probably remove the MakeFileCSA file and the other makefile

2021-02-01 19:27 UTC, greenscientist commented
I can. I was not sure if we were ready to make the transition to the build
system  directly.

(I'll try to remove the need to install autoconf-archive. I can commit the
necessary macro in the repo to remove the dependency)

On Mon, Feb 1, 2021 at 2:18 PM Geneviève Bastien <notifications@github.com>
wrote:

> Do you have autoconf-archive installed ?
>
> I did not, it thus now seems to work! With the resulting application in
> the src/ folder.
>
> Could you please update the README with all those steps? You can probably
> remove the MakeFileCSA file and the other makefile
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kaligrafy/trRouting/pull/19#issuecomment-771094153>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABDR5N3BO5U2WG57K4QCXLS435APANCNFSM4WPAE3EA>
> .
>

2021-02-01 19:32 UTC, tahini commented
Well, I may be too eager on this one :wink: I'll let @kaligrafy decide if we replace the build system entirely or keep the old makefiles too.

2021-02-01 19:52 UTC, kaligrafy commented
If it works, than no problem deleting the old makefiles ;-)

2021-02-02 22:40 UTC, greenscientist commented
PR updated with documentation update, Makefile cleanup and removing the need to install autoconf-archive

2021-02-03 14:04 UTC, tahini approved these changes
Awesome! That is great, thanks! I'll let @kaligrafy try it out on mac and make sure it works for him too.

2021-02-03 14:08 UTC, tahini commented
Also, could you add the signed-off-by at the end of your commits

2021-02-03 14:12 UTC, greenscientist commented
The signoff policy was not clear. Should have it documented in a
"Contributing" section of the documentation

On Wed, Feb 3, 2021 at 9:09 AM Geneviève Bastien <notifications@github.com>
wrote:

> Also, could you add the signed-off-by at the end of your commits
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kaligrafy/trRouting/pull/19#issuecomment-772537458>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABDR5KIGGB5PAJCKWAIEZLS5FKIRANCNFSM4WPAE3EA>
> .
>

2021-02-03 14:32 UTC, tahini commented
Well... I think the signoff policy starts now, with multiple contributors on the project ;-) But yeah, we should document it too

2021-02-03 14:49 UTC, greenscientist commented
(this last updated added signoff-by lines)

2021-02-05 13:54 UTC, merged