Move JourneyStep tuple to an actual class
chairemobilite/trRouting pull request #205
Opened 2022-11-21 03:12 UTC by greenscientist

(Only the last commit for this PR, it's based on 2 others)

Test with transition. Perf similar to previous commit.

2022-11-22 20:25 UTC, greenscientist commented
rebased

2022-11-23 18:14 UTC, tahini requested changes
Refactoring code focuses all the attention to that code... and its un-clarities... sorry about that...

2022-11-23 18:14 UTC, tahini commented on connection_scan_algorithm/include/journey_step.hpp
> +  class JourneyStep {
What does this class represent? Since enter and exit connections are optional, it can be any journey step, like access, egress, transfer, in vehicle, etc? Or does it imply a tranfers? Since there are transfer travel time and distances fields...

2022-11-23 18:14 UTC, tahini commented on connection_scan_algorithm/include/journey_step.hpp
> +    void setFinalEnterConnection(std::shared_ptr<Connection> _connection) {
I know it's a tuple turned into a class, but would it be desirable eventually to make these objects immutable? Or are setters necessary? (I'm thinking that setting a connection will potentially impact the transfer time and distance, so they need to be set together, no?)

If I'm totally mistaken, please reply to this comment, otherwise, you can add proper todos in the code or issues.

2022-11-23 18:14 UTC, tahini commented on connection_scan_algorithm/include/journey_step.hpp
> +    // Return true if both final and exit connections are valid
"enter* and exit". Also, by connection, you mean transfer? Doesn't an access/egress step have a connection, since at least enter or exit _connections_ are set? What does it mean to have both set vs only one?

2022-11-23 18:14 UTC, tahini commented on connection_scan_algorithm/src/forward_calculation.cpp
> +                     forwardEgressJourneysSteps.at(transferableNode.node.uid).getFinalExitConnection().value()->getArrivalTime() > connectionArrivalTime
Are you sure you have a value here?

2022-11-23 18:14 UTC, tahini commented on connection_scan_algorithm/src/forward_journey.cpp
> +          journey.push_back(JourneyStep(std::nullopt,std::nullopt,std::nullopt,nodesEgress.at(resultingNode.uid).distance,false,nodesEgress.at(resultingNode.uid).distance));
You could add some breathing space to those lines and add a whitespace after the commas. Same below.

2022-11-23 18:14 UTC, tahini commented on connection_scan_algorithm/src/forward_journey.cpp
> +          if (journeyStep.hasConnections())
If I look at the else, `hasConnections` is more `isTransitStep` or something like that, something not access/egress.

2022-11-23 18:14 UTC, tahini commented on connection_scan_algorithm/src/forward_journey.cpp
> +            if (journey.size() > i + 1 && journey[i+1].getFinalEnterConnection().has_value())
Also, why final? final in what sense? Why not just getEnterConnection?

2022-11-23 18:14 UTC, tahini commented on connection_scan_algorithm/src/forward_journey.cpp
> +            transferTime          = journeyStep.getTransferTravelTime();
The else says "access or egress journey step", but you get "transferTime". Would it be more "walkingTime" if you want to use it both for transfers and access/egress?

2022-11-23 18:14 UTC, tahini commented on connection_scan_algorithm/src/optimize_journey.cpp
> +                journey[fromJourneyStepIdx].setFinalExitConnection(exitConnection.value());
Previously, you were setting `exitConnection` and `connection`, but now, you set one with `exitConnection.value()` and the other with simply `connection`. Did the compiler miss something before or am I missing something here?

2022-11-23 18:14 UTC, tahini commented on connection_scan_algorithm/src/reverse_journey.cpp
> +          journey.push_front(JourneyStep(std::nullopt,std::nullopt,std::nullopt,nodesAccess.at(resultingNode.uid).time,false,nodesAccess.at(resultingNode.uid).distance));
white spaces here

2022-11-23 18:16 UTC, greenscientist commented on connection_scan_algorithm/include/journey_step.hpp
> +  class JourneyStep {
You'll have to ask @kaligrafy for an answer like that.

2022-11-23 18:17 UTC, greenscientist commented on connection_scan_algorithm/include/journey_step.hpp
> +    void setFinalEnterConnection(std::shared_ptr<Connection> _connection) {
No real idea. I just formalized that actions that were done in the code already.

2022-11-23 18:18 UTC, greenscientist commented on connection_scan_algorithm/include/journey_step.hpp
> +    // Return true if both final and exit connections are valid
another questin for @kaligrafy :)

2022-11-23 18:19 UTC, greenscientist commented on connection_scan_algorithm/src/forward_calculation.cpp
> +                     forwardEgressJourneysSteps.at(transferableNode.node.uid).getFinalExitConnection().value()->getArrivalTime() > connectionArrivalTime
I haven't checked the code yet, but I think it was one of the case where I was not 100% sure. At least value() throws an exception if there's no value, so we will catch it.

2022-11-23 18:19 UTC, greenscientist commented on connection_scan_algorithm/src/forward_journey.cpp
> +          journey.push_back(JourneyStep(std::nullopt,std::nullopt,std::nullopt,nodesEgress.at(resultingNode.uid).distance,false,nodesEgress.at(resultingNode.uid).distance));
Yeah, I just did not touch the previous code

2022-11-23 18:19 UTC, greenscientist commented on connection_scan_algorithm/src/forward_journey.cpp
> +          if (journeyStep.hasConnections())
Maybe :)

2022-11-23 18:20 UTC, greenscientist commented on connection_scan_algorithm/src/forward_journey.cpp
> +            if (journey.size() > i + 1 && journey[i+1].getFinalEnterConnection().has_value())
@kaligrafy ... :)

2022-11-23 18:20 UTC, greenscientist commented on connection_scan_algorithm/src/forward_journey.cpp
> +            transferTime          = journeyStep.getTransferTravelTime();
@kaligrafy

2022-11-23 18:23 UTC, greenscientist commented on connection_scan_algorithm/src/optimize_journey.cpp
> +                journey[fromJourneyStepIdx].setFinalExitConnection(exitConnection.value());
I think before was wrong somehow

2022-11-23 18:24 UTC, greenscientist commented on connection_scan_algorithm/src/optimize_journey.cpp
> +                journey[fromJourneyStepIdx].setFinalExitConnection(exitConnection.value());
(The tuple don't always type match correctly...)

2022-11-23 21:51 UTC, greenscientist commented on connection_scan_algorithm/include/journey_step.hpp
> +    void setFinalEnterConnection(std::shared_ptr<Connection> _connection) {
The setter are used in the optimise_journey code path. I don't have an high trust in that part of the code. 
(I don't think it's well covered in the current unit tests)

2022-11-24 20:40 UTC, kaligrafy commented on connection_scan_algorithm/include/journey_step.hpp
> +  class JourneyStep {
a journey step can be walking from origin to first stop, riding between stuff in vehicle, tansfering by foot and walking from last stop to destination

2022-11-24 20:41 UTC, kaligrafy commented on connection_scan_algorithm/include/journey_step.hpp
> +    void setFinalEnterConnection(std::shared_ptr<Connection> _connection) {
I really don't remember for setFinalEnterConnection

2022-11-24 20:42 UTC, kaligrafy commented on connection_scan_algorithm/include/journey_step.hpp
> +    // Return true if both final and exit connections are valid
no, enter connection is the connection use just afeter boarding. Exit connection is the last connection before unboarding

2022-11-24 20:43 UTC, kaligrafy commented on connection_scan_algorithm/src/forward_journey.cpp
> +            if (journey.size() > i + 1 && journey[i+1].getFinalEnterConnection().has_value())
the last exit connection will be the last used connection before egress

2022-11-24 20:44 UTC, kaligrafy commented on connection_scan_algorithm/src/forward_journey.cpp
> +            transferTime          = journeyStep.getTransferTravelTime();
yes this is walking time, but it also called transfer time

2022-11-24 20:44 UTC, kaligrafy commented on connection_scan_algorithm/src/forward_journey.cpp
> +            transferTime          = journeyStep.getTransferTravelTime();
Because you are walking to reach transferring stop. It should be 0 if transferring at same stop

2022-11-29 15:35 UTC, tahini commented on connection_scan_algorithm/include/journey_step.hpp
> +  class JourneyStep {
@greenscientist can you add this as comment above? With potentially a TODO if you think something should be done about the journey step type heterogeneity.

2022-11-29 15:35 UTC, tahini commented on connection_scan_algorithm/include/journey_step.hpp
> +    void setFinalEnterConnection(std::shared_ptr<Connection> _connection) {
I'm still confused here. If you think of any todos 2 to add here, please do...

2022-11-29 15:35 UTC, tahini commented on connection_scan_algorithm/include/journey_step.hpp
> +    // Return true if both final and exit connections are valid
@kaligrafy so which kind of step has connections? Only in-vehicle? Or transfers, access, egress too?

2022-11-29 15:35 UTC, tahini commented on connection_scan_algorithm/src/forward_calculation.cpp
> +                     forwardEgressJourneysSteps.at(transferableNode.node.uid).getFinalExitConnection().value()->getArrivalTime() > connectionArrivalTime
ok... anyway it's the same as before I guess

2022-11-29 15:35 UTC, tahini commented on connection_scan_algorithm/src/forward_journey.cpp
> +          if (journeyStep.hasConnections())
@kaligrafy Could you confirm what it means to have BOTH enter and exit connection? So that `hasConnections` can have a more meaningful name

2022-11-29 15:35 UTC, tahini commented on connection_scan_algorithm/src/forward_journey.cpp
> +            if (journey.size() > i + 1 && journey[i+1].getFinalEnterConnection().has_value())
But given the function name, ALL connections are final in this class, not just the last one. One of them happens to be the last one, but the step doesn't know that, it's the trip flow that will know which one. So having "final" in the function name may not be necessary? @kaligrafy?

2022-11-29 15:35 UTC, tahini commented on connection_scan_algorithm/src/forward_journey.cpp
> +            transferTime          = journeyStep.getTransferTravelTime();
So walking is tranferring in a transfer step, but walking is just walking in an access/egress step. So for the function name, `getWalkingTravelTime` or `getWalkingTravelDistance` would be more appropriate (since transfer is a concept that means something that isn't this). Or anything that means what it should and does not imply transferring from one line to the other.

2022-11-30 18:49 UTC, greenscientist commented on connection_scan_algorithm/include/journey_step.hpp
> +  class JourneyStep {
Adding comment and created #209

2022-11-30 18:50 UTC, greenscientist commented on connection_scan_algorithm/include/journey_step.hpp
> +    void setFinalEnterConnection(std::shared_ptr<Connection> _connection) {
Agreed, Added a TODO.

2022-11-30 18:51 UTC, greenscientist commented on connection_scan_algorithm/src/forward_calculation.cpp
> +                     forwardEgressJourneysSteps.at(transferableNode.node.uid).getFinalExitConnection().value()->getArrivalTime() > connectionArrivalTime
yeah

2022-11-30 18:56 UTC, greenscientist commented on connection_scan_algorithm/src/forward_journey.cpp
> +          journey.push_back(JourneyStep(std::nullopt,std::nullopt,std::nullopt,nodesEgress.at(resultingNode.uid).distance,false,nodesEgress.at(resultingNode.uid).distance));
Splited into separate lines

2022-11-30 19:00 UTC, greenscientist commented on connection_scan_algorithm/src/forward_journey.cpp
> +          if (journeyStep.hasConnections())
Added TODO

2022-11-30 19:08 UTC, greenscientist commented on connection_scan_algorithm/src/forward_journey.cpp
> +            transferTime          = journeyStep.getTransferTravelTime();
Ok, that's a strong question. I just copied/pasted in as a TODO.

2022-11-30 19:52 UTC, tahini approved these changes
Ok, sounds like lot of refactoring fun in perspective!

2022-11-30 19:53 UTC, greenscientist commented
haha, yes. But at least, I think we will be getting to some easy to understand code after that!

2022-11-30 19:53 UTC, merged