Various change to remove variables when unnecessary and simplify the calculator and other classes
chairemobilite/trRouting pull request #206
Opened 2022-11-21 22:03 UTC by greenscientist

(based on previous PR)

2022-11-23 18:15 UTC, tahini commented
Please rebase on latest v2c or wait until the other PR gets in before rebasing?

2022-11-23 18:25 UTC, greenscientist commented
Yes, I'm waiting for the JourneyStep PR to be done before rebasing

2022-11-23 21:58 UTC, greenscientist commented
(Did rebase on the current journeystep, make it easier to see which commits are only in this PR)

2022-11-30 21:02 UTC, tahini requested changes
Looks ok, except for some formatting comments and more comments needed (like always...)

2022-11-30 21:02 UTC, tahini commented on tests/connection_scan_algorithm/csa_result_to_response_test.hpp
> +  std::unique_ptr<TrRouting::Mode> mode;
These lines are not aligned with the rest

2022-11-30 21:02 UTC, tahini commented on include/routing_result.hpp
> +                   ): TransitRoutingStep(result_step_type::UNBOARDING, _trip, _legSequenceInTrip, _stopSequenceInTrip, _node),
It' s normal that the closing parenthesis is so far right?

2022-11-30 21:02 UTC, tahini commented on connection_scan_algorithm/include/calculator.hpp
> +    std::unique_ptr<RoutingResult> forwardJourneyStep(RouteParameters &parameters, int bestArrivalTime, std::optional<std::reference_wrapper<const Node>> bestEgressNode, const std::unordered_map<Node
Does the `const` before the `forwardEgressJourneySteps` imply that the content of the map cannot be modified in this function. Iiuc, this map will be filled in the forwardCalculation function? And used in the forwardJourneyStep? If so, please add a comment, that one method receives an empty map, the other expects it filled.

2022-11-30 21:05 UTC, greenscientist commented on connection_scan_algorithm/include/calculator.hpp
> +    std::unique_ptr<RoutingResult> forwardJourneyStep(RouteParameters &parameters, int bestArrivalTime, std::optional<std::reference_wrapper<const Node>> bestEgressNode, const std::unordered_map<Node
This is what a const imply. I would argue that a comment is not really needed to explicit that.

2022-11-30 21:07 UTC, tahini commented on connection_scan_algorithm/include/calculator.hpp
> +    std::unique_ptr<RoutingResult> forwardJourneyStep(RouteParameters &parameters, int bestArrivalTime, std::optional<std::reference_wrapper<const Node>> bestEgressNode, const std::unordered_map<Node
I thought the const implied the value, ie the map pointer, not its content. Or is that only for simple types?

2022-11-30 21:37 UTC, greenscientist commented on connection_scan_algorithm/include/calculator.hpp
> +    std::unique_ptr<RoutingResult> forwardJourneyStep(RouteParameters &parameters, int bestArrivalTime, std::optional<std::reference_wrapper<const Node>> bestEgressNode, const std::unordered_map<Node
You won't be able to add/remove elements to a const map. And you will only have access to const references for the elements.

2022-11-30 22:13 UTC, greenscientist commented on include/routing_result.hpp
> +                   ): TransitRoutingStep(result_step_type::UNBOARDING, _trip, _legSequenceInTrip, _stopSequenceInTrip, _node),
Yes, it's aligned with the opening one. But I can bring it back down.

2022-11-30 22:19 UTC, greenscientist commented on connection_scan_algorithm/include/calculator.hpp
> +    std::unique_ptr<RoutingResult> forwardJourneyStep(RouteParameters &parameters, int bestArrivalTime, std::optional<std::reference_wrapper<const Node>> bestEgressNode, const std::unordered_map<Node
added comment to the forward/reverveCalculation to specify that the journeySteps there is a return value also.

2022-12-01 00:08 UTC, tahini approved these changes

2022-12-01 00:08 UTC, tahini commented on connection_scan_algorithm/include/calculator.hpp
> +    std::unique_ptr<RoutingResult> forwardJourneyStep(RouteParameters &parameters, int bestArrivalTime, std::optional<std::reference_wrapper<const Node>> bestEgressNode, const std::unordered_map<Node
Thanks

2022-12-01 00:08 UTC, tahini commented on include/routing_result.hpp
> +                   ): TransitRoutingStep(result_step_type::UNBOARDING, _trip, _legSequenceInTrip, _stopSequenceInTrip, _node),
You align the parenthesis with the opening one, no matter how far down the line it is? Is that a C++ standard style? I'm used to languages where the formatting automatically aligns it by default to the right indent. Just asking...

2022-12-01 00:19 UTC, greenscientist commented
I usually align the thing inside the parenthesis to the opening one yes. 
That's how my emacs does it and it's configured by default. I don't think there's a strong consensus on that tho

2022-12-01 02:14 UTC, merged