v2: Add the `v2/accessibility` API route
chairemobilite/trRouting pull request #215
Opened 2022-12-02 21:18 UTC by tahini

This route is for the all_nodes of v1, with only the required parameters, a single place and the time query parameters are the same as the other calculation routes.

The response type is defined and the node's code and name are returned additionally, like the other API responses. Consumers don't necessarily have access to the data and the ID may not be meaningful.

2022-12-02 21:22 UTC, tahini commented on docs/APIv2/accessibilityResponse.yml
> +          - NO_ROUTING_FOUND,
Wondering if the next 2 are enough or if there's really need for this third reason... The code will tell... But yeah, maybe if we can reach a stop, wait for the bus, enter the bus, but we don't even reach the next stop within the requested time... I guess we can leave it

2022-12-02 21:54 UTC, greenscientist commented on docs/APIv2/accessibilityResponse.yml
> +        description: Time at which this node was reached, in seconds since midnight. This represents the departure time from node if time is the arrival, or arrival time if time is the departure
unsure if I understand well. 

Do you mean, in the second part, if the time *type" is arrival or arrival time if time *type* is departure ?

2022-12-02 22:30 UTC, tahini commented on docs/APIv2/accessibilityResponse.yml
> +        description: Time at which this node was reached, in seconds since midnight. This represents the departure time from node if time is the arrival, or arrival time if time is the departure
"if the requested time" would be more exact (time type is 0 or 1 to mean departure or arrival)

2022-12-02 22:36 UTC, greenscientist commented
Seem sane to me. Will leave around for the weekend in case @kaligrafy want to have a look.

2022-12-02 22:36 UTC, greenscientist approved these changes

2022-12-05 13:47 UTC, tahini commented on docs/APIv2/accessibilityResponse.yml
> +        $ref: '#/nodeAccessibility'
Il manque le pourcentage de noeuds accessibles. On a le nombre, mais le pourcentage permet de savoir combien de nombre au total ont été testés

2022-12-05 14:19 UTC, greenscientist requested changes

2022-12-05 14:19 UTC, greenscientist commented on docs/APIv2/accessibilityResponse.yml
> +        $ref: '#/nodeAccessibility'
C'est une partie que je trouvais un peu abérante dans le code. Pourrait-on mettre le nombre total de noeud à la place? Le pourcentage donne un nombre un peu imprécis, on peut laisser le client calculer le pourcentage...

Sinon, il faudrait préciser la précision du nombre qu'on met ici. C'est un float, donc par définition non exact.

2022-12-05 14:44 UTC, tahini commented on docs/APIv2/accessibilityResponse.yml
> +        $ref: '#/nodeAccessibility'
done

2022-12-05 15:10 UTC, greenscientist commented on docs/APIv2/accessibilityResponse.yml
> +        $ref: '#/nodeAccessibility'
Do we want to add a comment saying something along "totalNode is useful to calculate the percentage of node accessible" or that's not relevent to the API doc ?

2022-12-05 15:10 UTC, greenscientist approved these changes

2022-12-05 15:16 UTC, tahini commented on docs/APIv2/accessibilityResponse.yml
> +        $ref: '#/nodeAccessibility'
I don't think it's relevant for API doc, one can do whatever they want with this information!

2022-12-05 16:50 UTC, merged