v2: Do not repeat result status in each alternatives
chairemobilite/trRouting pull request #221
Opened 2022-12-08 13:35 UTC by tahini

In the alternatives route response, the status only appears at the root of the response. The query parameters are also only at the root of the response instead of repeated in each alternative.

2022-12-08 16:14 UTC, greenscientist requested changes
I don't have a great explanation for it, but I really don't like the use of a flag "status_required" in this implementation. 
Maybe it's just the name of the flag that does not fit well. 
Maybe we just need to drop the whole concept of the visitors (which we will be able to do)

2022-12-08 16:15 UTC, greenscientist commented
I think the things that's worrying the most, is that we should have a derived class for the AlternativeResult processing.

2022-12-08 16:24 UTC, tahini commented
> I don't have a great explanation for it, but I really don't like the use of a flag "status_required" in this implementation. Maybe it's just the name of the flag that does not fit well. Maybe we just need to drop the whole concept of the visitors (which we will be able to do)

Indeed, as I start thinking of the implementation of the other endoint's return values, I think the visitor, at least for the base response, was not such a great idea after all (for steps, it is ok). Each endpoint has a slightly different implementation (see the route vs summary) and some of the classes simply throw a "Does not make sense to be here" exception. Static functions specific for each endpoint would probably be sufficient. But that's what we have now...

2022-12-08 16:29 UTC, tahini reviewed
Since I'm about to implement an actual client that makes use of that API, I'd like for it not to be too beta... so let's clarify once and almost for all!

2022-12-08 16:29 UTC, tahini commented on docs/APIv2/routeResponse.yml
> +    - $ref: '#/baseRouteResponse'
In the idea, like in the odTrips, to differentiate calculated responses from query data, should the baseRouteResponse be under a single field, eg. `query`, and all the rest would be calculated fields? In which case, should also the responses be under a clean `result` field?

eg:
```
{ status: 'success', query: { ... query params }, result: { alternatives: [...], alternativesTotal: } }

2022-12-08 16:31 UTC, tahini commented
@greenscientist If the implementation of the API's result bugs you, we could concentrate on clarifying the API and I can rewrite all results_to_v2 implementations later.

2022-12-08 17:05 UTC, greenscientist commented on docs/APIv2/routeResponse.yml
> +    - $ref: '#/baseRouteResponse'
I'm really wondering, why are we sending back the query again? 
(My main question is is that helpful? If it might be easier to differenciate queries when we send a lot, ok, sure, but will we do that?

2022-12-08 17:09 UTC, tahini commented on docs/APIv2/routeResponse.yml
> +    - $ref: '#/baseRouteResponse'
1- It confirms that the query parameters are ok (like if you get an unexpected reverse origin lat/lon, you might realize you messed up the query) and what was calculated is really what was expected. 
2- And eventually, we will do a lot of queries, when we can and it's parallel.

2022-12-09 16:46 UTC, tahini commented
As discussed, all API endpoints will have the base response format of: 
```
  status: list_of_statuses,
  query: reminder of query parameters
  result: If status is success, there should be something,
  reason: If status is not success, one of various possible reason
```

Each endpoint will document each of those fields.

2022-12-09 18:10 UTC, tahini commented
All current endpoint definitions have been updated.

2022-12-09 18:22 UTC, greenscientist commented on docs/APIv2/accessibilityResponse.yml
> +      $ref: '#/accessibilityResponse'
Should we call that accessiblityResultResponse ? (To mark the different from the Query response)

2022-12-09 18:24 UTC, tahini commented on docs/APIv2/accessibilityResponse.yml
> +      $ref: '#/accessibilityResponse'
Sure! I guess the comment applies to all...

2022-12-09 18:24 UTC, greenscientist commented on docs/APIv2/routeResponse.yml
>  routeOrAlternativesResponse:
I'm not a fan of this routeOrAlternative Response, can we split it up ? So it's clear that we are getting either a single route or a list of alternative?
I would be open to have 2 differents endpoints if they are not already splitted.

2022-12-09 18:29 UTC, greenscientist commented on docs/APIv2/accessibilityResponse.yml
> +      $ref: '#/accessibilityResponse'
yeah, let's make it more uniform.

2022-12-09 18:50 UTC, tahini commented on docs/APIv2/routeResponse.yml
>  routeOrAlternativesResponse:
thinking, thinking............ We could also do like osrm-backend's route endpoints and return an array of alternative in every case. Just with only 1 result if alternatives is false. That would make it simpler for everyone. As a client, if you're only interested in the first result, you just use this one. This would seemlessly make the odTrips route support both alternatives or not (see one comment in that commit)

2022-12-09 18:51 UTC, greenscientist commented on docs/APIv2/routeResponse.yml
>  routeOrAlternativesResponse:
Yeah, I think I would be happy with that. Will need a good description, but seem simple enough.

2022-12-09 19:14 UTC, tahini commented on docs/APIv2/routeResponse.yml
> -  - $ref: '#/baseRouteResponse'
no need for allOf here

2022-12-09 19:23 UTC, greenscientist approved these changes
Feels its in a good shape. 

We might want to add in a document a description of the general structure of each response (Status, Query, Result). but can be added later as we continue working on it.

2022-12-09 19:32 UTC, merged