Implementation of the v2/accessibility
chairemobilite/trRouting pull request #231
Opened 2022-12-19 16:13 UTC by tahini

2022-12-19 16:54 UTC, tahini commented
@kaligrafy Please, could you look at the last commit here to see if I'm saying anything silly: https://github.com/chairemobilite/trRouting/pull/231/commits/7fddf0acebe2365d0d15c5884522b500c38cda38

2022-12-19 17:44 UTC, kaligrafy commented
Perfect!

2022-12-19 18:08 UTC, greenscientist requested changes
A few things, mostly in the code organisation category

2022-12-19 18:08 UTC, greenscientist commented on include/parameters.hpp
> +  class BaseParameters {
I think I would have called it CommonParameters instead, but it's not important enough to change. 
But can you add a comment with a short description to explain that this is for the common parts of parameters.

2022-12-19 18:08 UTC, greenscientist commented on include/parameters.hpp
> +      BaseParameters(const Scenario& scenario,
I think we could set the constructor as protected, so that we prohibit the instantion of only a baseparameter object.

2022-12-19 18:08 UTC, greenscientist commented on connection_scan_algorithm/src/Makefile.am
> +		   parameters_base.cpp \
Please, name them the same way as the class. (route_parmeters.cpp)  Or rename the class to be ParametersRoute

2022-12-19 18:08 UTC, greenscientist commented on connection_scan_algorithm/src/Makefile.am
> +		   parameters_base.cpp \
If you have done this to ease the organisation, eventually all the parameter stuff can be into its own directory.

2022-12-19 18:08 UTC, greenscientist commented on connection_scan_algorithm/src/parameters_accessibility.cpp
> +      else if (parameterWithValue.first == "time_of_trip")
Isn't these thing common with Route?  They should probably be parsed in a common function

2022-12-19 18:08 UTC, greenscientist commented on connection_scan_algorithm/include/constants.hpp
> +// No routing reasons
Feels weird to have that in a generic contant.hpp file. Could we have a more specific place?

Could be a result_common.hpp file

2022-12-19 18:08 UTC, greenscientist commented on connection_scan_algorithm/include/constants.hpp
> +// No routing reasons
Are they somewhat defined in a common file in the API.yml file? I want to ease the matching between the API definition and the code

2022-12-19 18:08 UTC, greenscientist commented on connection_scan_algorithm/include/calculator.hpp
> +    void reset(BaseParameters &parameters, std::optional<std::reference_wrapper<const Point>> origin, std::optional<std::reference_wrapper<const Point>> destination, bool resetAccessPaths = true, boo
Ouf. Hopefully we'll get rid of reset() soon...

2022-12-19 21:47 UTC, tahini commented on connection_scan_algorithm/include/constants.hpp
> +// No routing reasons
No, for the API yml file, each endpoint has its own enum of the no routing reason, they are not the same for each, there's a few differences (for the no service and no access). I didn't want to add another .hpp file, but why not!

2022-12-19 21:49 UTC, tahini commented on connection_scan_algorithm/src/Makefile.am
> +		   parameters_base.cpp \
Yes, I wanted all the parameters related files to be next to each other not to have to search for parameters test, but indeed another directory could work. Do I need an additional Makefile.am for this directory too or  just put the dir/file.ccp here?

2022-12-19 22:19 UTC, greenscientist commented on connection_scan_algorithm/src/Makefile.am
> +		   parameters_base.cpp \
For simplicity, you can put the dir/file cpp here. 

It would be a bit cleaner to create a Makefile.am there, but then we'd need to make and manage libraries.

2022-12-20 14:15 UTC, tahini commented on connection_scan_algorithm/src/parameters_accessibility.cpp
> +      else if (parameterWithValue.first == "time_of_trip")
I'll use aggregation instead of inheritance, it will allow to more easily parse the common parameters

2022-12-20 21:05 UTC, greenscientist approved these changes
Still a few things to changes, but that's mostly just comments and smallist thing, so accepting.

2022-12-20 21:05 UTC, greenscientist commented on connection_scan_algorithm/src/od_trips_routing.cpp
> +          parameters);
This parameters was confusing me a little bit. 
Maybe add a comment saying that we reuse the common part of the original request. 
(I was where this parameters come from, we don't have a CommonParameter around...)

2022-12-20 21:05 UTC, greenscientist commented on include/parameters.hpp
> +   * @brief Helper function to get an integer value from a string, or throw a
while you are here, could you add to the comment
from a string, using std::stoi, or throw...

I went around wondering why we don't use the std::stoi directly, but it seems we want a fonction that convert the exception.

2022-12-20 21:05 UTC, greenscientist commented on connection_scan_algorithm/src/parameters/common_parameters.cpp
> +  int getIntegerValue(std::string strValue) {
I need to add myself a TODO to add the ability to have the key name in the exception thrown here.

2022-12-20 21:05 UTC, greenscientist commented on include/parameters.hpp
> +  int getIntegerValue(std::string strValue);
Might worth it to add a TODO here to put this function into a base class for all parameter instead of having it floating around.

2022-12-20 21:05 UTC, greenscientist commented on connection_scan_algorithm/include/result_to_v2_accessibility.hpp
> +#include "routing_result.hpp"
Does not seem to be necessary in the .hpp, can be added simply to the necessary .cpp file.

2022-12-21 02:29 UTC, tahini commented on include/parameters.hpp
> +   * @brief Helper function to get an integer value from a string, or throw a
This is just the function declaration, we don't know that the implementation will be using std::stoi.

2022-12-21 03:00 UTC, tahini commented on connection_scan_algorithm/include/result_to_v2_accessibility.hpp
> +#include "routing_result.hpp"
It is necessary for the NoRoutingReason enum

2022-12-21 16:50 UTC, greenscientist commented on include/parameters.hpp
> +   * @brief Helper function to get an integer value from a string, or throw a
The thing is without this information, there's no reason to have a getIntegerValue function. We should just use std::stol directly. So we need some explanation about why this function exist.

2022-12-21 16:51 UTC, greenscientist commented on connection_scan_algorithm/include/result_to_v2_accessibility.hpp
> +#include "routing_result.hpp"
ok my bad, confused routing_result and result_constant.

2022-12-21 17:42 UTC, tahini commented on include/parameters.hpp
> +   * @brief Helper function to get an integer value from a string, or throw a
I added some comments, but the contract for the create*Parameters says to throw a ParameterException if the parameter values are missing or invalid. You can use std::stoi directly, but you have to handle and convert the exceptions yourself.

2022-12-21 19:19 UTC, greenscientist commented on include/parameters.hpp
> +   * @brief Helper function to get an integer value from a string, or throw a
thanks

2022-12-21 19:19 UTC, merged