performance: Cache connections by scenario
chairemobilite/trRouting pull request #238
Opened 2023-02-17 22:41 UTC by tahini

Fixes #237

This caches the connections for the queried scenario. Only the last queried scenario is kept to avoid having to manage cache eviction and memory usage.

At the beginning of the calculation, in the resetFilters step, the connection cache object is retrieved, and computed if a new scenario is requested. This object contains only the forward and reverse connections for this scenario. All others are ignored.

For instances with a lot of services this improves performance. For example, calculations are 75% faster for an instance that contained the complete Montreal area data for fall 2018 and 2019.

2023-02-17 22:53 UTC, tahini commented
Friday evening code dump!

It appears to work, I added some unit tests, but haven't proof-read the code yet. Between const disqualifiers, shared_ptr and reference_wrappers, I'm just happy it finally compiles and works!

More tests are needed probably. @greenscientist  If you have a chance to get a quick look to let me know if there's anything fundamentally wrong here, let me know

2023-02-19 01:56 UTC, kaligrafy commented
What is the performance gain when switching scenario compared to before? I mean how much time it takes to filter the connections for a specific scenario + looping the connections vs only looping all connections?

2023-02-20 15:04 UTC, tahini commented
> What is the performance gain when switching scenario compared to before? I mean how much time it takes to filter the connections for a specific scenario + looping the connections vs only looping all connections?

Indeed, the first request for a scenario takes visibly longer, though subsequent requests are much faster. I'm not sure why, but there's probably something I can improve in this PR...

2023-02-20 15:25 UTC, kaligrafy commented
Could we create the filtered connections vector by scenario at the launch of the server so we don't need to filter later on? It would increase a bit the memory, but if you put pointers in the vectors, it should be small enough even for a large number of scenarios?

2023-02-20 16:28 UTC, tahini commented
Oddly enough, with small instances (where almost all connections are in the scenario), it takes longer with this patch than before (though I didn't try real benchmarks yet). I wasn't expecting any time gain or loss in that case (except on first run for scenario). But I'll run the real original benchmarks to have real data.

Also, about caching all scenarios at load, it doesn't scale, but trRouting doesn't scale anyway... I'll have to see how big the memory will increase if doing so with the eod complete instance. More benchmarking to do!

2023-02-20 16:41 UTC, kaligrafy commented
Or at least keep the previously used scenarios until a threshold or something, and then throw oldest filetered connections data.

2023-02-20 18:05 UTC, tahini commented
> Or at least keep the previously used scenarios until a threshold or something, and then throw oldest filetered connections data.

That’s the long term idea, but an lru cache is hard to implement and requires a lot of testing. This is to get quick results for our batch calculation users.

2023-02-20 19:28 UTC, tahini commented
For memory usage data, here's the memory usage of trRouting, while in action (ie with one cached scenario), with and without this PR. Sizes are in megabytes:

|    | v2c | This PR | overhead
|---|---|---|---
| benchmark data | 173 | 192 | 11%
| Small instance | 203 | 242 | 19%
| Large instance (eod) | 1946 | 1993 | 2.4%

2023-02-21 15:27 UTC, greenscientist requested changes
We can fix the const correctness, no need to remove it. 

And yes, after reading the rest of the code, we need to rename to object ConnectionCache to something else. 
Also Implement the ScenarioCache into a separate .hpp/cpp

2023-02-21 15:27 UTC, greenscientist commented on connection_scan_algorithm/include/calculator.hpp
> +    // FIXME const was removed because calling getConnectionCacheForScenario apparently discards its const qualifier
We'll need to investigate that a bit more. 

Some time, with caching, using the mutable keyword is acceptable.

2023-02-21 15:27 UTC, greenscientist commented on connection_scan_algorithm/include/journey_step.hpp
> +    JourneyStep(std::optional<std::reference_wrapper<Connection>> _finalEnterConnection,
Would be interesting to do the switch from share_ptr to reference_wrapper as a separate commit.

2023-02-21 15:27 UTC, greenscientist commented on connection_scan_algorithm/include/journey_step.hpp
> +    void setFinalEnterConnection(Connection&  _connection) {
Not const?

2023-02-21 15:27 UTC, greenscientist commented on connection_scan_algorithm/src/forward_journey.cpp
> +          Connection& journeyStepEnterConnection = journeyStep.getFinalEnterConnection().value().get();
I'm surprise that I had left them outside of if. You verified there was not another object with the same name that was masqued?

2023-02-21 15:27 UTC, greenscientist commented on include/connection_cache.hpp
> +class ConnectionCache {
You'll need at least a comment to describe the class

2023-02-21 15:27 UTC, greenscientist commented on include/connection_cache.hpp
> +class ScenarioConnectionCache {
How does this relate to ConnectionCache ? With a name like that I would have expected some inheritance

2023-02-21 15:27 UTC, greenscientist commented on include/connection_cache.hpp
> +    std::shared_ptr<ConnectionCache> lastConnection;
This tells me that ConnectionCache is not a cache, but a Connection "Collection". The class does not manage the caching mecanism

2023-02-21 15:27 UTC, greenscientist commented on include/transit_data.hpp
> +    std::shared_ptr<ConnectionCache> getConnectionCacheForScenario(const Scenario & scenario);
Yeah, this should be const, with some mutable cache object inside it.

2023-02-22 20:19 UTC, tahini commented
@greenscientist consts are back, reference_wrapper of const objects are extracted, ConnectionCache is renamed to ConnectionSet, with comments for each class. And the class is unit tested.

2023-02-22 21:10 UTC, greenscientist requested changes

2023-02-22 21:10 UTC, greenscientist commented on tests/connection_scan_algorithm/csa_test_data_fetcher.hpp
> +    inline static const boost::uuids::uuid scenario2Uuid = uuidGenerator("11111111-2222-2345-789a-555555666667");
Details, but I think it would be nice to add somewhere an assert that scenarioUuid != scenario2Uuid. 

(Just to make sure we don't accidentaly make them the same)

2023-02-22 21:10 UTC, greenscientist commented on connection_scan_algorithm/include/calculator.hpp
> +    std::shared_ptr<ConnectionSet> connectionSet;
Can have a small comment about it

2023-02-22 21:10 UTC, greenscientist commented on connection_scan_algorithm/include/calculator.hpp
> +    std::shared_ptr<ConnectionSet> connectionSet;
I would had more comments about the name of this variable, but it will need to be moved out of the Calculator object to make the calculator multithreaded, so we'll make the change later.

2023-02-22 21:10 UTC, greenscientist commented on include/connection_cache.hpp
> +#ifndef TR_CONNECTION_CACHE
Can you split this file? Each class their file.

2023-02-22 21:10 UTC, greenscientist commented on src/connection_cache.cpp
> +  // Create a cache with a begin iterator which match the connection closest to the specified hour
I don't see a red part in other file for this code, but I think it's a copy/paste, is that expected

2023-02-23 14:50 UTC, tahini commented
The comments are addressed. Today I'll investigate removing code from the old code path and what can be so long for the first scenario request. That can be done as part of this PR or in another one on top of it, as you prefer. But as is, it works and is standalone.

2023-02-23 15:30 UTC, greenscientist commented
If you want to do the removal of the old code as a separate PR then we will need comments in this one about the copy/paste, where the code came from and also a TODO about code removal. 
It's really hard to follow code moving like that in a git blame, so we need to leave bread crumbs

2023-02-23 16:37 UTC, greenscientist approved these changes
ok looks good

2023-02-23 16:40 UTC, merged