Remove osrm lib requirement
chairemobilite/trRouting pull request #44
Opened 2021-05-03 19:07 UTC by kaligrafy

2021-05-17 21:36 UTC, greenscientist commented on .gitignore
> +/src/.dirstamp
What is that?

2021-05-17 21:44 UTC, greenscientist commented on src/osrm_fetcher.cpp
> +      int numberOfDistances = responseJson["distances"][0].size();
I'm curious about this change, I struggle to see how it's related to removing the OSRMlib

2021-05-17 21:44 UTC, greenscientist commented on README.md
> +[Open Source Routing Machine (OSRM)][3] (an osrm server with a walking profile must be running for the transit region while making queries to the trRouting server)
Maybe we should add a bit more details on what it's need to run?  Could be a link to another document

2021-05-17 21:44 UTC, greenscientist commented on Dockerfile
> -# We need the osrm-backend lib to build trRouting so we rely on a fork of the official image
This will break the Dockfile in the transition project. It's ok, raising so people are aware. I've created an issue in the project to adapt it when this is pushed to production.

2021-05-18 16:55 UTC, kaligrafy commented on src/osrm_fetcher.cpp
> +      int numberOfDistances = responseJson["distances"][0].size();
Wow, I don't remember having changed that in a while... This needs more testing.

2021-05-18 16:56 UTC, kaligrafy commented on Dockerfile
> -# We need the osrm-backend lib to build trRouting so we rely on a fork of the official image
ok

2021-05-18 16:56 UTC, kaligrafy commented on README.md
> +[Open Source Routing Machine (OSRM)][3] (an osrm server with a walking profile must be running for the transit region while making queries to the trRouting server)
We could copy this readme part from transition

2021-05-18 16:57 UTC, kaligrafy commented on .gitignore
> +/src/.dirstamp
I don't know, I tought it was a file created by the compiler...

2021-05-18 16:57 UTC, kaligrafy commented on .gitignore
> +/src/.dirstamp
Yes indeed, Automake generates an empty .dirstamp file

2021-05-18 17:01 UTC, kaligrafy commented on src/osrm_fetcher.cpp
> +      int numberOfDistances = responseJson["distances"][0].size();
fixed in bdbb9c540879991cb2226f4a5be93e19f0d8f9ad

2021-05-20 18:13 UTC, kaligrafy commented on README.md
> +[Open Source Routing Machine (OSRM)][3] (an osrm server with a walking profile must be running for the transit region while making queries to the trRouting server)
added

2021-05-20 18:16 UTC, kaligrafy commented
Please review again. Thanks!

2021-05-20 18:41 UTC, greenscientist commented on .gitignore
> +/src/.dirstamp
ok, never seen that before, but ok!

2021-05-20 18:43 UTC, merged

2021-05-20 18:45 UTC, greenscientist requested changes

2021-05-20 18:45 UTC, greenscientist commented on src/osrm_fetcher.cpp
> +      int numberOfDistances = responseJson["distances"][0].size();
You still have the extra [0] insome of the line there. Was it broken before or it's still untested code?

2021-05-20 18:45 UTC, greenscientist commented
Requested change, just to have an answer to the addition of an array indexing in the json response. (You removed some of the lines, but there's other.

2021-05-20 18:46 UTC, greenscientist commented
Hey! You have merged without a PR approuval

2021-05-20 18:59 UTC, kaligrafy commented on src/osrm_fetcher.cpp
> +      int numberOfDistances = responseJson["distances"][0].size();
The correct way is with the index 0. It was not broken before, because the variables were initialized outside the loop first and never used inside the loop.

2021-05-20 20:11 UTC, greenscientist commented on src/osrm_fetcher.cpp
> +      int numberOfDistances = responseJson["distances"][0].size();
It's not that there were never used. They are used inside the loop, but they were redefined. (I missed that part and your comment have confused me a little bit ;-) )

2021-05-20 21:08 UTC, kaligrafy commented on src/osrm_fetcher.cpp
> +      int numberOfDistances = responseJson["distances"][0].size();
So it is correct? Can we close this?

2021-05-20 21:09 UTC, greenscientist commented
You already pushed it...

On Thu, May 20, 2021 at 5:08 PM Pierre-Léo Bourbonnais <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/osrm_fetcher.cpp
> <https://github.com/kaligrafy/trRouting/pull/44#discussion_r636471437>:
>
> >        //std::cout << "numberOfDurations: " << responseJson["durations"][0].dump(2) << std::endl;
> -      int numberOfDistances = responseJson["distances"].size();
> +      int numberOfDistances = responseJson["distances"][0].size();
>
> So it is correct? Can we close this?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/kaligrafy/trRouting/pull/44#discussion_r636471437>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABDR5NJWWBTR25NEKJGFTTTOV26FANCNFSM44BK3YMQ>
> .
>

2021-06-30 20:51 UTC, tahini commented
This PR broke compilation with ubuntu... I don't understand why...