When using od trips routing, initial lost time at departure was not
chairemobilite/trRouting pull request #51
Opened 2021-06-18 12:31 UTC by kaligrafy

available in the routing results. This commit adds the variable so we
can export it for each routed od trip

2021-07-19 20:11 UTC, greenscientist requested changes
Need a few fix up.

2021-07-19 20:11 UTC, greenscientist commented on connection_scan_algorithm/src/reverse_journey.cpp
> +      result.nonTransitTravelTimeSeconds = -1;
This is a duplicate of the previous line

2021-07-19 20:11 UTC, greenscientist commented on include/routing_result.hpp
>      int arrivalTimeSeconds;
Could be interesting to make it a class, so we can have a proper initialization for all field. 
And not have to copy paste and keep in sync in multiple place

2021-07-19 20:11 UTC, greenscientist commented on connection_scan_algorithm/src/forward_journey.cpp
>        result.departureTimeSeconds        = departureTimeSeconds;
You dont have     result.initialDepartureTimeSeconds = -1;  here
￼

2021-07-23 14:00 UTC, kaligrafy commented on connection_scan_algorithm/src/reverse_journey.cpp
> +      result.nonTransitTravelTimeSeconds = -1;
fixed

2021-07-23 14:00 UTC, kaligrafy commented on include/routing_result.hpp
>      int arrivalTimeSeconds;
I'll open an issue for this

2021-07-23 14:01 UTC, kaligrafy commented on connection_scan_algorithm/src/forward_journey.cpp
>        result.departureTimeSeconds        = departureTimeSeconds;
fixed

2021-07-26 22:03 UTC, greenscientist commented on connection_scan_algorithm/src/forward_journey.cpp
> +            result.initialLostTimeAtDepartureSeconds = minimizedDepartureTime - departureTimeSeconds;
Do you really need to add this in the struct since you can compute it from 2 others values already stored?

2021-07-26 22:37 UTC, kaligrafy commented on connection_scan_algorithm/src/forward_journey.cpp
> +            result.initialLostTimeAtDepartureSeconds = minimizedDepartureTime - departureTimeSeconds;
I think yes, because the end-user can download the csv including these fields and I want to make sure they calculate it correctly

2021-08-03 18:04 UTC, greenscientist approved these changes
Ok, will follow up task #78

2021-08-04 09:50 UTC, merged