Add a new nearestOsrmNodeNetworkDistance to access and egress steps
chairemobilite/trRouting pull request #62
Opened 2021-07-13 18:27 UTC by kaligrafy

Useful to know if the origin and/or destination is far from the osrm network.

2021-07-19 20:36 UTC, greenscientist requested changes
Would be great to make those std::tuple<int,int,int,int,int,short,int,int>  into actual object so that we have an idea of what they are. 

Did a quick lock, there's a few things to improve, might find more things  later

2021-07-19 20:36 UTC, greenscientist commented on connection_scan_algorithm/include/calculator.hpp
> +    std::vector<std::tuple<int,int,int,int>> accessFootpaths; // pair: accessNodeIndex, walkingTravelTimeSeconds, walkingDistanceMeters, nearest osrm node distance from point (only for acees and egre
typo in the comments

2021-07-19 20:36 UTC, greenscientist commented on connection_scan_algorithm/src/reverse_journey.cpp
> +      int journeyStepTravelTime    {-1}; int accessWalkingTime      {-1}; int nearestNetworkNodeDistanceMeters { -1};
You don't really need to put those outside the for loop if you are initializing them at every loop

2021-07-19 20:36 UTC, greenscientist commented on connection_scan_algorithm/src/reverse_journey.cpp
> +        waitingTime                 = -1; accessWaitingTime      = -1; nearestDestinationNodeDistanceMeters = -1;
Please, don't  put multiple statement on the same line. 
Should also have accessWaitingTime multiple time

2021-07-19 20:36 UTC, greenscientist commented on src/osrm_fetcher.cpp
> +      int nearestNetworkNodeDistanceMeters = (int)ceil((float)responseJson["sources"][0]["distance"]); // the distance in meters between point and nearest osrm routable node
Have  you tested this ? responseJson is probably a string, you cannot just convert with (float)

2021-07-19 20:51 UTC, kaligrafy commented
About the tuple, when I wrote this code, it was faster to use tuples instead of objects... We should test the performance to see if it is necessary to use a tuple

2021-07-19 22:25 UTC, tahini commented
A good set of benchmarks will allow us to test all this stuff real soon! @YasmineMoumou !!

2021-07-20 15:31 UTC, greenscientist commented
> About the tuple, when I wrote this code, it was faster to use tuples instead of objects... We should test the performance to see if it is necessary to use a tuple

Sure, but they can also be at least behind a typedef or a #define. Each individual int can also be a typedef. 
The aim of the comment was to point how hard is it to understand the code at the moment with all these tuple. Coupled with a general lack of comments, this is really tricky

2021-07-23 00:36 UTC, kaligrafy commented on src/osrm_fetcher.cpp
> +      int nearestNetworkNodeDistanceMeters = (int)ceil((float)responseJson["sources"][0]["distance"]); // the distance in meters between point and nearest osrm routable node
the distance attribute is always a float value

2021-07-23 01:58 UTC, greenscientist commented on src/osrm_fetcher.cpp
> +      int nearestNetworkNodeDistanceMeters = (int)ceil((float)responseJson["sources"][0]["distance"]); // the distance in meters between point and nearest osrm routable node
Je vais devoir aller lire la documentation de nlohmann::json
But in addition, we should not use C style casting in C++

2021-07-23 13:42 UTC, kaligrafy commented
Can I rebase this and open a new issue to deal with formatting and typedefs?

2021-07-23 14:07 UTC, kaligrafy commented on src/osrm_fetcher.cpp
> +      int nearestNetworkNodeDistanceMeters = (int)ceil((float)responseJson["sources"][0]["distance"]); // the distance in meters between point and nearest osrm routable node
added an issue for this

2021-07-23 14:07 UTC, kaligrafy commented on connection_scan_algorithm/include/calculator.hpp
> +    std::vector<std::tuple<int,int,int,int>> accessFootpaths; // pair: accessNodeIndex, walkingTravelTimeSeconds, walkingDistanceMeters, nearest osrm node distance from point (only for acees and egre
fixed

2021-07-23 14:08 UTC, kaligrafy commented on connection_scan_algorithm/src/reverse_journey.cpp
> +        waitingTime                 = -1; accessWaitingTime      = -1; nearestDestinationNodeDistanceMeters = -1;
Added an issue for this

2021-07-26 21:41 UTC, greenscientist commented on src/osrm_fetcher.cpp
> +      int nearestNetworkNodeDistanceMeters = (int)ceil((float)responseJson["sources"][0]["distance"]); // the distance in meters between point and nearest osrm routable node
What about
responseJson["sources"][0]["distance"].get<int>();

2021-08-02 18:47 UTC, kaligrafy commented
I would let you guys try to test and fix the C style casting issue as I am not good enough in C++ to do that efficiently

2024-04-30 15:24 UTC, greenscientist commented
@kaligrafy, can you create an issue with what you were trying to achieve here ? The changed changed a lot, so we cannot just try to apply this PR. I'll close the PR then and we can try to reimplement it.

2024-04-30 15:29 UTC, closed without merging