Add bird distance accessibilitity implementation
chairemobilite/trRouting pull request #79
Opened 2021-08-02 20:15 UTC by YasmineMoumou

This PR closes #55.

Changes:

2021-08-03 14:05 UTC, tahini requested changes
iiuc, in this PR, you are not really adding the bird distance implementation, but refactoring the code to allow the bird distance to be used to get reachable nodes. Please make sure to update the commit message to reflect that.

Also, you 2 commits are not really independent, you can merge them in one, using interactive rebase `git rebase -i HEAD~2` and fixup the last one into the previous one.

2021-08-03 14:05 UTC, tahini commented on src/osrm_fetcher.cpp
> +    float lengthOfOneDegreeOfLongitude = 111412.84 * cos(point.latitude * M_PI / 180) -93.5 * cos (3 * point.latitude * M_PI / 180);
I know you did not write these lines, but where do 111412.84 come from? and 93.5? and the numbers of the line below? If @kaligrafy can answer those questions, you may add it as comments in this method. Also the numbers could be extracted to constants with meaningful names

2021-08-03 14:05 UTC, tahini commented on src/osrm_fetcher.cpp
> +  std::vector<std::tuple<int,int,int>> OsrmFetcher::getNodesFromOsmr(const Point& point, const std::vector<std::unique_ptr<Node>>& nodes, std::string mode, Parameters& params, bool reversed)
rename to getNodesFromOsrm, not Osmr

2021-08-03 14:05 UTC, tahini commented on include/osrm_fetcher.hpp
> +    static std::vector<std::tuple<int,int,int>> getNodesFromOsmr(const Point& point, const std::vector<std::unique_ptr<Node>>& nodes, std::string mode, Parameters& params, bool reversed);
osmr => osrm

2021-08-03 14:05 UTC, tahini commented on src/osrm_fetcher.cpp
> +    } else
in this project, the else is on a separate line
```
}
else
{
```

2021-08-03 14:05 UTC, tahini commented on src/osrm_fetcher.cpp
> +      distanceMetersSquared = calculateNodeDistanceSquared(node->point.get(), point, lengthOfOneDegree);
A good part of this method is a copy of the getNodesFromBirdDistance. Could you call the getNodesFromBirdDistance, then loop through the the results to build the query string instead?

2021-08-03 14:05 UTC, tahini commented on include/osrm_fetcher.hpp
> +    private:
I haven't done much C++ recently, but do we need to add the private methods here in the .hpp? Or are they implementation details that need only be in the .cpp file? @greenscientist  may know better.

2021-08-03 14:20 UTC, kaligrafy commented on src/osrm_fetcher.cpp
> +    float lengthOfOneDegreeOfLongitude = 111412.84 * cos(point.latitude * M_PI / 180) -93.5 * cos (3 * point.latitude * M_PI / 180);
It is explained [here](https://physics.wooster.edu/Manz/sandcollection/swaplist/Latitude%20and%20Longitude.pdf), but these number do not represent a physicial value exactly, they are just constants in the equation.

2021-08-03 14:24 UTC, kaligrafy commented on src/osrm_fetcher.cpp
> +    float lengthOfOneDegreeOfLongitude = 111412.84 * cos(point.latitude * M_PI / 180) -93.5 * cos (3 * point.latitude * M_PI / 180);
We don't add the last part 0.118 cos(5 theta)), since it would change the longitude less than +/-11.8 cm

2021-08-03 14:28 UTC, kaligrafy commented on src/osrm_fetcher.cpp
> +    float lengthOfOneDegreeOfLongitude = 111412.84 * cos(point.latitude * M_PI / 180) -93.5 * cos (3 * point.latitude * M_PI / 180);
These are the factors of a Taylor series approximation

2021-08-03 14:32 UTC, tahini commented on src/osrm_fetcher.cpp
> +    float lengthOfOneDegreeOfLongitude = 111412.84 * cos(point.latitude * M_PI / 180) -93.5 * cos (3 * point.latitude * M_PI / 180);
Are those numbers specific to our latitude? Or would this calculation work where in the world?

2021-08-03 14:35 UTC, kaligrafy commented on src/osrm_fetcher.cpp
> +    float lengthOfOneDegreeOfLongitude = 111412.84 * cos(point.latitude * M_PI / 180) -93.5 * cos (3 * point.latitude * M_PI / 180);
in theory it works anywhere

2021-08-03 15:22 UTC, greenscientist commented on src/osrm_fetcher.cpp
> +    float lengthOfOneDegreeOfLongitude = 111412.84 * cos(point.latitude * M_PI / 180) -93.5 * cos (3 * point.latitude * M_PI / 180);
Yeah,  source for these numbers needs to be put at least in comment in the code. And idealy as constant.

2021-08-03 15:25 UTC, greenscientist commented on include/osrm_fetcher.hpp
> +    private:
If they are part of the class, they will need to be in the .hpp file. 
But since they are static, they could be helper function only in the .cpp file also. 
Also it's really rare that we need to set something like this as private, protected is usually better, so they can be used by derived classes.

2021-08-03 15:27 UTC, greenscientist commented on include/osrm_fetcher.hpp
> +    private:
Also, purely math function should probably be put into an utility class outside of the osrm class

2021-08-03 18:13 UTC, YasmineMoumou commented
> iiuc, in this PR, you are not really adding the bird distance implementation, but refactoring the code to allow the bird distance to be used to get reachable nodes. Please make sure to update the commit message to reflect that.
> 
> Also, you 2 commits are not really independent, you can merge them in one, using interactive rebase `git rebase -i HEAD~2` and fixup the last one into the previous one.

I can just squash them at the end into one?

2021-08-03 19:28 UTC, YasmineMoumou commented on src/osrm_fetcher.cpp
> +      distanceMetersSquared = calculateNodeDistanceSquared(node->point.get(), point, lengthOfOneDegree);
The method getNodesFromOsrm requires more than just what getNodesFromBirdDistance returns in the accessibleNodesFootpaths vector, it requires the node itself to form the query. To seperate the two i had to have the loop through the nodes in both methods. Initially there was only one loop, but i separated them following your comment about having an if statement that redirects to the correct implementation in the main getAccessibleNodesFootpathsFromPoint method. I can retract to having a singe loop but if i do that, I will not have what you initially asked for.

2021-08-03 19:33 UTC, YasmineMoumou commented on src/osrm_fetcher.cpp
> +      distanceMetersSquared = calculateNodeDistanceSquared(node->point.get(), point, lengthOfOneDegree);
To remove some the dupplication i can take out the lines: 

    auto lengthOfOneDegree = calculateLengthOfOneDegree(point);
    float maxDistanceMetersSquared = calculateMaxDistanceSquared(params);

and place them before the method calls in getAccessibleNodesFootpathsFromPoint, but then i have to add 2 more parameters o both methods and i think there are already a lot.

2021-08-03 19:49 UTC, YasmineMoumou commented on src/osrm_fetcher.cpp
> +    float lengthOfOneDegreeOfLongitude = 111412.84 * cos(point.latitude * M_PI / 180) -93.5 * cos (3 * point.latitude * M_PI / 180);
I think a comment is more suiting here because otherwise there will be 10 constants all used only once in this method.

2021-08-03 20:13 UTC, YasmineMoumou commented on include/osrm_fetcher.hpp
> +    private:
These methods are only used in this class. I can make them protected to leave the possibility of them being used by derived classes open, though from what i know, i don't think it will be needed.

2021-08-03 21:27 UTC, tahini requested changes
One last small comment to improve a comment ;-)

Otherwise, what have you tested this with?

2021-08-03 21:27 UTC, tahini commented on src/osrm_fetcher.cpp
> +      distanceMetersSquared = calculateNodeDistanceSquared(node->point.get(), point, lengthOfOneDegree);
Ok, that's already great improvement to be able to be osrm independent. Eventually, we may split the osrmFetcher into to accessibleNodes  implementations, one using osrm, the other not, but for now, it's enough.

2021-08-03 21:27 UTC, tahini commented on src/osrm_fetcher.cpp
> +    // First two terms of the Taylor series of the longitude and latitude length functions
It's worth adding a link to something here. I tried to google what you wrote and couldn't find anything satisfactory. This link may be more helpful? https://gis.stackexchange.com/questions/75528/understanding-terms-in-length-of-degree-formula

For something algorithmic and using constants like this, it is worth putting a link to documentation on where the terms come from. The people reading this code may come from all kinds of background and may not be familiar with the geography or the math. A simple explanation makes it all clear!

2021-08-04 19:25 UTC, YasmineMoumou commented on include/osrm_fetcher.hpp
> +    private:
Conclusion: We keep the math methods here because there are not used elsewhere

2021-08-06 19:56 UTC, merged