Add a basic unit tests for the CSA algorithm
chairemobilite/trRouting pull request #94
Opened 2021-12-09 18:33 UTC by tahini

This moves the benchmarks to its own directory, leaving the connection_scan_algorithm directory available for unit tests.

It adds basic unit test data, with one agency and 2 lines.

This PR bootstraps the test, prepares the data set and has only one successful calculation with basic parameters. More tests will be added soon, to test various use cases

2021-12-09 19:11 UTC, kaligrafy approved these changes

2021-12-09 20:25 UTC, greenscientist requested changes
Main issue is the name of the function in the second commit. 

Maybe the test data could live in it's own commit with a more detailled explaination on how it was generated, but I can be wrong on this.

2021-12-09 20:25 UTC, greenscientist commented on connection_scan_algorithm/include/calculator.hpp
> +    void nodeDataImported();
I don't think the past tense is appropriate for an "action" function. Maybe importNodeData instead?

2021-12-09 20:25 UTC, greenscientist commented on connection_scan_algorithm/src/initializations.cpp
> +  void Calculator::nodeDataImported() {
I don't see any importation in this function. Is  the name appropriate?

2021-12-09 20:25 UTC, greenscientist commented on connection_scan_algorithm/src/initializations.cpp
> +    int hour {0};
I know you only copy/pasted the code, but I wonder why those initialization are not in the for()

2021-12-09 20:25 UTC, greenscientist commented on connection_scan_algorithm/src/initializations.cpp
> +    for (auto & connection : forwardConnections)
Should  those for loops also splited on their only functions?

2021-12-09 20:25 UTC, greenscientist commented on connection_scan_algorithm/src/initializations.cpp
> +    for (auto & connection : forwardConnections)
Optional but if you have a chance, you can comment out on what they do

2021-12-09 20:25 UTC, greenscientist commented on connection_scan_algorithm/include/calculator.hpp
> +    void nodeDataImported();
Should those function really be public? What happen if you call them at any time?

2021-12-09 20:25 UTC, greenscientist commented on tests/connection_scan_algorithm/csa_simple_calculation_test.cpp
> +#include "gtest/gtest.h" // we will add the path to C preprocessor later
I don't  understand this comment.

2021-12-09 20:25 UTC, greenscientist commented on tests/connection_scan_algorithm/csa_test_base.hpp
> +    TrRouting::Calculator calculator;
It feels strange the have those those object as part of the test object. I think it would be better if they are created as part of the setup(). It might be a side effect of the current design of the TrRouting code.

2021-12-09 20:25 UTC, greenscientist commented on tests/connection_scan_algorithm/csa_test_base.hpp
> +    // but specific test cases can override these methods and add their own data
Nice

2021-12-09 20:43 UTC, tahini commented on connection_scan_algorithm/include/calculator.hpp
> +    void nodeDataImported();
They should not, they're public only because of the unit tests! Most of the fields in this class can be split into different structures/classes: Data objects (agencies, lines, corresponding maps, etc), calculation objects (the ones that need to be modified by those 2 methods), parameter objects (I'm working on it in a separate branch)

If you call them anytime, it will just reset the nodes fields. You don't do that during a calculation, it's not thread safe, but we have a single thread, so...

2021-12-09 20:45 UTC, tahini commented on connection_scan_algorithm/include/calculator.hpp
> +    void nodeDataImported();
These functions do not import, but are to be called after the node data is imported, whence the past tense... I could put them both in a single method and call it resetInternalData. It could also be part of the current reset method: if the size of the array modified and the nodes do not match, reset them all.

2021-12-09 20:50 UTC, greenscientist commented on connection_scan_algorithm/include/calculator.hpp
> +    void nodeDataImported();
Yeah, their name should reflect what they do and not in what stated the object is

2021-12-09 20:50 UTC, tahini commented on tests/connection_scan_algorithm/csa_simple_calculation_test.cpp
> +#include "gtest/gtest.h" // we will add the path to C preprocessor later
haha me neither, but it's everywhere we have this include because we always copy-paste it!!

2021-12-09 20:55 UTC, greenscientist commented on tests/connection_scan_algorithm/csa_simple_calculation_test.cpp
> +#include "gtest/gtest.h" // we will add the path to C preprocessor later
Yeah, I was afraid that I wrote that down originally and not remember what it meant

2021-12-09 20:57 UTC, tahini commented
Thanks for the feedback

> Maybe the test data could live in it's own commit with a more detailled explaination on how it was generated, but I can be wrong on this.

By test data, you mean the gtfs files? Or the base_csa_test.cpp which adds the data object?

2021-12-09 21:00 UTC, greenscientist commented
> > Maybe the test data could live in it's own commit with a more detailled explaination on how it was generated, but I can be wrong on this.
> 
> By test data, you mean the gtfs files? Or the base_csa_test.cpp which adds the data object?

I was thinking of the content of tests/connection_scan_algorithm/unit_test_data_gtfs/

But the more I think about it, I'm not sure I would know how to go from the data to the data object in the code. Maybe the code need more comments.

2021-12-09 21:06 UTC, tahini commented
> I was thinking of the content of tests/connection_scan_algorithm/unit_test_data_gtfs/
> 
> But the more I think about it, I'm not sure I would know how to go from the data to the data object in the code. Maybe the code need more comments.

I put the data there because one can easily zip those files (I didn't want to put the zip binary files in git, so it's unzipped here) and import it in Transition to visualize the nodes and network and add some stuff. But it is not required. The unit test data should remain manual and manually modifiable.

2021-12-09 21:08 UTC, greenscientist commented
> > I was thinking of the content of tests/connection_scan_algorithm/unit_test_data_gtfs/
> > But the more I think about it, I'm not sure I would know how to go from the data to the data object in the code. Maybe the code need more comments.
> 
> I put the data there because one can easily zip those files (I didn't want to put the zip binary files in git, so it's unzipped here) and import it in Transition to visualize the nodes and network and add some stuff. But it is not required. The unit test data should remain manual and manually modifiable.

Yeah, it's good that way. I juste think we miss some documentation about the steps you have put to go from there to the data in the tests. (and maybe how to reimport in transition and do modification). 
I'm trying to think about our next intern who will to do more tests :)

2021-12-09 21:11 UTC, tahini commented on tests/connection_scan_algorithm/csa_test_base.cpp
> + * geographical data into account.
I will have some documentation here on what to do with this to re-import in Transition

2021-12-10 16:12 UTC, tahini commented on connection_scan_algorithm/include/calculator.hpp
> +    std::vector<std::shared_ptr<std::tuple<int,int,int,int,int,short,short,int,int,int,short,short>>> reverseConnections; // tuple: departureNodeIndex, arrivalNodeIndex, departureTimeSeconds, arrival
I think the sorting is very important, otherwise, currently, I don't get the expected data. So I'll replace making this public by a public methods that sets connections, ie will fill the forwardConnections and reverseConnections vectors, sort them and assign them to the trips.

2021-12-10 21:18 UTC, tahini commented
#96 is prerequisite and this will be rebased on it later, and add additional tests.

2021-12-17 15:59 UTC, tahini commented on tests/connection_scan_algorithm/csa_test_base.hpp
> +#endif // _CACHE_FETCHER_TEST_H
Wrong comment at the end

2022-01-06 20:35 UTC, greenscientist approved these changes
Just did a quick re-read, but looks good

2022-01-06 20:51 UTC, merged