csa: Initialize all fields in the calculator constructor
chairemobilite/trRouting pull request #98
Opened 2022-01-04 21:54 UTC by tahini

It is a rule to initialize all fields of a class in a constructor,
otherwise they may be assigned random values that happen to be in memory
when constructing the object.

The main code path was not affected since there's only one instance of
the Calculator constructed at the beginning of the program. But in unit
tests, it is causing bizarre failures of unrelated tests

2022-01-04 22:25 UTC, kaligrafy approved these changes

2022-01-06 16:39 UTC, greenscientist requested changes
I'd argue that all the objectname() are unnecessary since they will be called automatically by the object creation. 
But the one with non default value sure they are needed. 

Thoughts? Disagreements?

2022-01-06 17:46 UTC, tahini commented
> I'd argue that all the objectname() are unnecessary since they will be called automatically by the object creation. But the one with non default value sure they are needed.
> 
> Thoughts? Disagreements?

@greenscientist Your expertise in c++ will be helpful here: the original problem I had that made me do this patch, was that in the unit test, the constructor was called and reassigned memory for this object and probably at the location of the odTrip pointer, there was junk data and the pointer had a value, which caused errors in tests using the object. Will all non-pointer fields be automatically assigned with default constructor? Or will be they simply point to some memory location that may contain data that will make it think the vector is not empty? I've been reading this https://isocpp.org/wiki/faq/ctors#init-lists before doing this patch. It doesn't mention the case of 50 fields in a class though... ;-)

2022-01-06 18:15 UTC, greenscientist commented
So anythying that as a constructor will get initialized automatically. 
Other things like pointers, int, floats, etc. Need a manual init. 

For example: 

#include <iostream>

class B {
public:
  B() {
    std::cout << "B INIT" << std::endl;
  }
};

class A {
public:
  A() {
    std::cout << "A INIT" << std::endl;
  }
  B test;
};

int main() {
  A toto;
}

./a.out 
B INIT
A INIT

2022-01-06 21:47 UTC, kaligrafy approved these changes

2022-01-11 16:11 UTC, greenscientist approved these changes
Ok

One thing that the early version of this diff highligts is that there's way too many data objects in thie Calculator class!

2022-01-11 18:03 UTC, tahini commented
> One thing that the early version of this diff highligts is that there's way too many data objects in thie Calculator class!

Issue #95 tracks this. These PRs are preparation for the "parameters field" task, but the rest should come soon too.

2022-01-11 18:03 UTC, merged